stages:
  - lint
  - build
  - cts

build_trigger_job:
  rules:
    - if: ($CI_PIPELINE_SOURCE != "merge_request_event") && ($CI_COMMIT_BRANCH == 'master')
  stage: build
  variables:
    # the build script assumes it's run from a MR context
    CI_MERGE_REQUEST_TARGET_BRANCH_NAME: master
    CI_MERGE_REQUEST_PROJECT_URL: ${CI_SERVER_URL}/android_translation_layer/aports
    # for artifact archive name
    UPSTREAM_COMMIT: $CI_COMMIT_SHA
  trigger:
    project: android_translation_layer/aports
    branch: atl-nightlies-atl
    strategy: depend

cts_trigger_job:
  rules:
    - if: ($CI_PIPELINE_SOURCE != "merge_request_event") && ($CI_COMMIT_BRANCH == 'master')
  stage: cts
  trigger:
    project: android_translation_layer/android_translation_layer.gitlab.io
    branch: master

lint:
  stage: lint
  rules:
    - if: ($CI_PIPELINE_SOURCE == "merge_request_event")
  script:
    - mkdir clang_format_artifact
    - curl -Lo clang_format_artifact/clang_format_artifact.zip https://gitlab.com/android_translation_layer/clang-format/-/jobs/artifacts/atl_changes/download?job=build-x86_64
    - unzip -d clang_format_artifact/ clang_format_artifact/clang_format_artifact.zip
    - find src/ -type f -exec clang_format_artifact/build/bin/clang-format -Werror --dry-run {} +
  tags:
    - saas-linux-small-amd64
