/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_content_ClipboardManager */

#ifndef _Included_android_content_ClipboardManager
#define _Included_android_content_ClipboardManager
#ifdef __cplusplus
extern "C" {
#endif
#undef android_content_ClipboardManager_MSG_REPORT_PRIMARY_CLIP_CHANGED
#define android_content_ClipboardManager_MSG_REPORT_PRIMARY_CLIP_CHANGED 1L
/*
 * Class:     android_content_ClipboardManager
 * Method:    native_set_clipboard
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_content_ClipboardManager_native_1set_1clipboard
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
