/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_view_WindowManagerImpl */

#ifndef _Included_android_view_WindowManagerImpl
#define _Included_android_view_WindowManagerImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_view_WindowManagerImpl
 * Method:    native_addView
 * Signature: (JIIIII)V
 */
JNIEXPORT void JNICALL Java_android_view_WindowManagerImpl_native_1addView
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     android_view_WindowManagerImpl
 * Method:    native_updateViewLayout
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_android_view_WindowManagerImpl_native_1updateViewLayout
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     android_view_WindowManagerImpl
 * Method:    native_removeView
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_view_WindowManagerImpl_native_1removeView
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
