/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_atl_ATLKeyboardDialog */

#ifndef _Included_android_atl_ATLKeyboardDialog
#define _Included_android_atl_ATLKeyboardDialog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_atl_ATLKeyboardDialog
 * Method:    nativeInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_atl_ATLKeyboardDialog_nativeInit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
