/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_os_MemoryFile */

#ifndef _Included_android_os_MemoryFile
#define _Included_android_os_MemoryFile
#ifdef __cplusplus
extern "C" {
#endif
#undef android_os_MemoryFile_PROT_READ
#define android_os_MemoryFile_PROT_READ 1L
#undef android_os_MemoryFile_PROT_WRITE
#define android_os_MemoryFile_PROT_WRITE 2L
/*
 * Class:     android_os_MemoryFile
 * Method:    native_open
 * Signature: (Ljava/lang/String;I)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_android_os_MemoryFile_native_1open
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     android_os_MemoryFile
 * Method:    native_mmap
 * Signature: (Ljava/io/FileDescriptor;II)I
 */
JNIEXPORT jint JNICALL Java_android_os_MemoryFile_native_1mmap
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     android_os_MemoryFile
 * Method:    native_munmap
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_android_os_MemoryFile_native_1munmap
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_os_MemoryFile
 * Method:    native_close
 * Signature: (Ljava/io/FileDescriptor;)V
 */
JNIEXPORT void JNICALL Java_android_os_MemoryFile_native_1close
  (JNIEnv *, jclass, jobject);

/*
 * Class:     android_os_MemoryFile
 * Method:    native_read
 * Signature: (Ljava/io/FileDescriptor;I[BIIIZ)I
 */
JNIEXPORT jint JNICALL Java_android_os_MemoryFile_native_1read
  (JNIEnv *, jclass, jobject, jint, jbyteArray, jint, jint, jint, jboolean);

/*
 * Class:     android_os_MemoryFile
 * Method:    native_write
 * Signature: (Ljava/io/FileDescriptor;I[BIIIZ)V
 */
JNIEXPORT void JNICALL Java_android_os_MemoryFile_native_1write
  (JNIEnv *, jclass, jobject, jint, jbyteArray, jint, jint, jint, jboolean);

/*
 * Class:     android_os_MemoryFile
 * Method:    native_pin
 * Signature: (Ljava/io/FileDescriptor;Z)V
 */
JNIEXPORT void JNICALL Java_android_os_MemoryFile_native_1pin
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     android_os_MemoryFile
 * Method:    native_get_size
 * Signature: (Ljava/io/FileDescriptor;)I
 */
JNIEXPORT jint JNICALL Java_android_os_MemoryFile_native_1get_1size
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
