/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_util_Log */

#ifndef _Included_android_util_Log
#define _Included_android_util_Log
#ifdef __cplusplus
extern "C" {
#endif
#undef android_util_Log_VERBOSE
#define android_util_Log_VERBOSE 2L
#undef android_util_Log_DEBUG
#define android_util_Log_DEBUG 3L
#undef android_util_Log_INFO
#define android_util_Log_INFO 4L
#undef android_util_Log_WARN
#define android_util_Log_WARN 5L
#undef android_util_Log_ERROR
#define android_util_Log_ERROR 6L
#undef android_util_Log_ASSERT
#define android_util_Log_ASSERT 7L
#undef android_util_Log_LOG_ID_MAIN
#define android_util_Log_LOG_ID_MAIN 0L
#undef android_util_Log_LOG_ID_RADIO
#define android_util_Log_LOG_ID_RADIO 1L
#undef android_util_Log_LOG_ID_EVENTS
#define android_util_Log_LOG_ID_EVENTS 2L
#undef android_util_Log_LOG_ID_SYSTEM
#define android_util_Log_LOG_ID_SYSTEM 3L
/*
 * Class:     android_util_Log
 * Method:    println_native
 * Signature: (IILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_android_util_Log_println_1native
  (JNIEnv *, jclass, jint, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
