/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_atl_GVariantIterParcel */

#ifndef _Included_android_atl_GVariantIterParcel
#define _Included_android_atl_GVariantIterParcel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_atl_GVariantIterParcel
 * Method:    native_readByte
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_android_atl_GVariantIterParcel_native_1readByte
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_atl_GVariantIterParcel
 * Method:    native_readInt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_android_atl_GVariantIterParcel_native_1readInt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_atl_GVariantIterParcel
 * Method:    native_readString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_android_atl_GVariantIterParcel_native_1readString
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
