/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_widget_PopupMenu */

#ifndef _Included_android_widget_PopupMenu
#define _Included_android_widget_PopupMenu
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_widget_PopupMenu
 * Method:    native_init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_widget_PopupMenu_native_1init
  (JNIEnv *, jobject);

/*
 * Class:     android_widget_PopupMenu
 * Method:    native_insertItem
 * Signature: (JILjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_android_widget_PopupMenu_native_1insertItem
  (JNIEnv *, jobject, jlong, jint, jstring, jint);

/*
 * Class:     android_widget_PopupMenu
 * Method:    native_insertSubmenu
 * Signature: (JILjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_android_widget_PopupMenu_native_1insertSubmenu
  (JNIEnv *, jobject, jlong, jint, jstring, jlong);

/*
 * Class:     android_widget_PopupMenu
 * Method:    native_removeItem
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_android_widget_PopupMenu_native_1removeItem
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     android_widget_PopupMenu
 * Method:    native_buildPopover
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_android_widget_PopupMenu_native_1buildPopover
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_widget_PopupMenu
 * Method:    native_show
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_android_widget_PopupMenu_native_1show
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
