/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_location_LocationManager */

#ifndef _Included_android_location_LocationManager
#define _Included_android_location_LocationManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_location_LocationManager
 * Method:    nativeGetLocation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_location_LocationManager_nativeGetLocation
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
