/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_Region */

#ifndef _Included_android_graphics_Region
#define _Included_android_graphics_Region
#ifdef __cplusplus
extern "C" {
#endif
#undef android_graphics_Region_MAX_POOL_SIZE
#define android_graphics_Region_MAX_POOL_SIZE 10L
/*
 * Class:     android_graphics_Region
 * Method:    isRect
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Region_isRect
  (JNIEnv *, jobject);

/*
 * Class:     android_graphics_Region
 * Method:    isComplex
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Region_isComplex
  (JNIEnv *, jobject);

/*
 * Class:     android_graphics_Region
 * Method:    contains
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Region_contains
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     android_graphics_Region
 * Method:    quickContains
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Region_quickContains
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     android_graphics_Region
 * Method:    quickReject
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Region_quickReject__IIII
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     android_graphics_Region
 * Method:    quickReject
 * Signature: (Landroid/graphics/Region;)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Region_quickReject__Landroid_graphics_Region_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     android_graphics_Region
 * Method:    translate
 * Signature: (IILandroid/graphics/Region;)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Region_translate
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     android_graphics_Region
 * Method:    scale
 * Signature: (FLandroid/graphics/Region;)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Region_scale
  (JNIEnv *, jobject, jfloat, jobject);

/*
 * Class:     android_graphics_Region
 * Method:    nativeEquals
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Region_nativeEquals
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_graphics_Region
 * Method:    nativeDestructor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Region_nativeDestructor
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_graphics_Region
 * Method:    nativeSetRegion
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Region_nativeSetRegion
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_graphics_Region
 * Method:    nativeSetRect
 * Signature: (IIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Region_nativeSetRect
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     android_graphics_Region
 * Method:    nativeSetPath
 * Signature: (IJI)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Region_nativeSetPath
  (JNIEnv *, jclass, jint, jlong, jint);

/*
 * Class:     android_graphics_Region
 * Method:    nativeGetBounds
 * Signature: (ILandroid/graphics/Rect;)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Region_nativeGetBounds
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     android_graphics_Region
 * Method:    nativeGetBoundaryPath
 * Signature: (IJ)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Region_nativeGetBoundaryPath
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     android_graphics_Region
 * Method:    nativeOp
 * Signature: (IIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Region_nativeOp__IIIIII
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     android_graphics_Region
 * Method:    nativeOp
 * Signature: (ILandroid/graphics/Rect;II)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Region_nativeOp__ILandroid_graphics_Rect_2II
  (JNIEnv *, jclass, jint, jobject, jint, jint);

/*
 * Class:     android_graphics_Region
 * Method:    nativeOp
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Region_nativeOp__IIII
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     android_graphics_Region
 * Method:    nativeToString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_android_graphics_Region_nativeToString
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
