/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_media_AudioManager */

#ifndef _Included_android_media_AudioManager
#define _Included_android_media_AudioManager
#ifdef __cplusplus
extern "C" {
#endif
#undef android_media_AudioManager_STREAM_MUSIC
#define android_media_AudioManager_STREAM_MUSIC 3L
/*
 * Class:     android_media_AudioManager
 * Method:    nativeSetStreamVolume
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_android_media_AudioManager_nativeSetStreamVolume
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
