/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_drawable_Drawable */

#ifndef _Included_android_graphics_drawable_Drawable
#define _Included_android_graphics_drawable_Drawable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_graphics_drawable_Drawable
 * Method:    native_paintable_from_path
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_drawable_Drawable_native_1paintable_1from_1path
  (JNIEnv *, jclass, jstring);

/*
 * Class:     android_graphics_drawable_Drawable
 * Method:    native_constructor
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_drawable_Drawable_native_1constructor
  (JNIEnv *, jobject);

/*
 * Class:     android_graphics_drawable_Drawable
 * Method:    native_invalidate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_graphics_drawable_Drawable_native_1invalidate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_graphics_drawable_Drawable
 * Method:    native_draw
 * Signature: (JJII)V
 */
JNIEXPORT void JNICALL Java_android_graphics_drawable_Drawable_native_1draw
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     android_graphics_drawable_Drawable
 * Method:    native_ref
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_graphics_drawable_Drawable_native_1ref
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_graphics_drawable_Drawable
 * Method:    native_unref
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_graphics_drawable_Drawable_native_1unref
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
