/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_Path */

#ifndef _Included_android_graphics_Path
#define _Included_android_graphics_Path
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_graphics_Path
 * Method:    native_create_builder
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_Path_native_1create_1builder
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     android_graphics_Path
 * Method:    native_create_path
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_Path_native_1create_1path
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Path
 * Method:    native_ref_path
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_Path_native_1ref_1path
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Path
 * Method:    native_reset
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1reset
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     android_graphics_Path
 * Method:    native_close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Path
 * Method:    native_move_to
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1move_1to
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     android_graphics_Path
 * Method:    native_line_to
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1line_1to
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     android_graphics_Path
 * Method:    native_cubic_to
 * Signature: (JFFFFFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1cubic_1to
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Path
 * Method:    native_quad_to
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1quad_1to
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Path
 * Method:    native_arc_to
 * Signature: (JFFFFFFZ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1arc_1to
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jboolean);

/*
 * Class:     android_graphics_Path
 * Method:    native_rel_move_to
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1rel_1move_1to
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     android_graphics_Path
 * Method:    native_rel_line_to
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1rel_1line_1to
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     android_graphics_Path
 * Method:    native_rel_cubic_to
 * Signature: (JFFFFFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1rel_1cubic_1to
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Path
 * Method:    native_rel_quad_to
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1rel_1quad_1to
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Path
 * Method:    native_add_arc
 * Signature: (JFFFFFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1add_1arc
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Path
 * Method:    native_add_path
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1add_1path
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     android_graphics_Path
 * Method:    native_add_rect
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1add_1rect
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Path
 * Method:    native_add_round_rect
 * Signature: (JFFFF[F)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1add_1round_1rect
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloatArray);

/*
 * Class:     android_graphics_Path
 * Method:    native_get_bounds
 * Signature: (JLandroid/graphics/RectF;)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Path_native_1get_1bounds
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     android_graphics_Path
 * Method:    native_transform
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_Path_native_1transform
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
