/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_inputmethodservice_InputMethodService_ATLInputConnection */

#ifndef _Included_android_inputmethodservice_InputMethodService_ATLInputConnection
#define _Included_android_inputmethodservice_InputMethodService_ATLInputConnection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_inputmethodservice_InputMethodService_ATLInputConnection
 * Method:    nativeInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_inputmethodservice_InputMethodService_00024ATLInputConnection_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     android_inputmethodservice_InputMethodService_ATLInputConnection
 * Method:    nativeSetCompositingText
 * Signature: (JLjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_android_inputmethodservice_InputMethodService_00024ATLInputConnection_nativeSetCompositingText
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     android_inputmethodservice_InputMethodService_ATLInputConnection
 * Method:    nativeSetCompositingRegion
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_android_inputmethodservice_InputMethodService_00024ATLInputConnection_nativeSetCompositingRegion
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     android_inputmethodservice_InputMethodService_ATLInputConnection
 * Method:    nativeFinishComposingText
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_android_inputmethodservice_InputMethodService_00024ATLInputConnection_nativeFinishComposingText
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_inputmethodservice_InputMethodService_ATLInputConnection
 * Method:    nativeCommitText
 * Signature: (JLjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_android_inputmethodservice_InputMethodService_00024ATLInputConnection_nativeCommitText
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     android_inputmethodservice_InputMethodService_ATLInputConnection
 * Method:    nativeDeleteSurroundingText
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_android_inputmethodservice_InputMethodService_00024ATLInputConnection_nativeDeleteSurroundingText
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     android_inputmethodservice_InputMethodService_ATLInputConnection
 * Method:    nativeSetSelection
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_android_inputmethodservice_InputMethodService_00024ATLInputConnection_nativeSetSelection
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     android_inputmethodservice_InputMethodService_ATLInputConnection
 * Method:    nativeSendKeyEvent
 * Signature: (JJJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_android_inputmethodservice_InputMethodService_00024ATLInputConnection_nativeSendKeyEvent
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
