/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_media_SoundPool */

#ifndef _Included_android_media_SoundPool
#define _Included_android_media_SoundPool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_media_SoundPool
 * Method:    native_constructor
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_media_SoundPool_native_1constructor
  (JNIEnv *, jclass);

/*
 * Class:     android_media_SoundPool
 * Method:    nativeLoad
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_android_media_SoundPool_nativeLoad
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     android_media_SoundPool
 * Method:    nativePlay
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_android_media_SoundPool_nativePlay
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
