/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_atl_ATLMediaContentProvider */

#ifndef _Included_android_atl_ATLMediaContentProvider
#define _Included_android_atl_ATLMediaContentProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_atl_ATLMediaContentProvider
 * Method:    native_open_media_folder
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_atl_ATLMediaContentProvider_native_1open_1media_1folder
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
