/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_drawable_NinePatchDrawable */

#ifndef _Included_android_graphics_drawable_NinePatchDrawable
#define _Included_android_graphics_drawable_NinePatchDrawable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_graphics_drawable_NinePatchDrawable
 * Method:    nativeCreate
 * Signature: ([BJ)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_drawable_NinePatchDrawable_nativeCreate___3BJ
  (JNIEnv *, jobject, jbyteArray, jlong);

/*
 * Class:     android_graphics_drawable_NinePatchDrawable
 * Method:    nativeCreate
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_drawable_NinePatchDrawable_nativeCreate__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     android_graphics_drawable_NinePatchDrawable
 * Method:    nativeSetTint
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_android_graphics_drawable_NinePatchDrawable_nativeSetTint
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
