/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_text_Layout */

#ifndef _Included_android_text_Layout
#define _Included_android_text_Layout
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_text_Layout
 * Method:    native_constructor
 * Signature: (Ljava/lang/String;JI)J
 */
JNIEXPORT jlong JNICALL Java_android_text_Layout_native_1constructor
  (JNIEnv *, jclass, jstring, jlong, jint);

/*
 * Class:     android_text_Layout
 * Method:    native_set_width
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_android_text_Layout_native_1set_1width
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     android_text_Layout
 * Method:    native_get_width
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_android_text_Layout_native_1get_1width
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_text_Layout
 * Method:    native_get_height
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_android_text_Layout_native_1get_1height
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_text_Layout
 * Method:    native_get_line_count
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_android_text_Layout_native_1get_1line_1count
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_text_Layout
 * Method:    native_get_line_start
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_android_text_Layout_native_1get_1line_1start
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     android_text_Layout
 * Method:    native_get_line_end
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_android_text_Layout_native_1get_1line_1end
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     android_text_Layout
 * Method:    native_get_line_top
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_android_text_Layout_native_1get_1line_1top
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     android_text_Layout
 * Method:    native_get_line_bottom
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_android_text_Layout_native_1get_1line_1bottom
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     android_text_Layout
 * Method:    native_get_line_left
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_android_text_Layout_native_1get_1line_1left
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     android_text_Layout
 * Method:    native_get_line_right
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_android_text_Layout_native_1get_1line_1right
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     android_text_Layout
 * Method:    native_get_line_width
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_android_text_Layout_native_1get_1line_1width
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     android_text_Layout
 * Method:    native_get_line_baseline
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_android_text_Layout_native_1get_1line_1baseline
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     android_text_Layout
 * Method:    native_get_line_ascent
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_android_text_Layout_native_1get_1line_1ascent
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     android_text_Layout
 * Method:    native_get_line_descent
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_android_text_Layout_native_1get_1line_1descent
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     android_text_Layout
 * Method:    native_get_line_for_vertical
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_android_text_Layout_native_1get_1line_1for_1vertical
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     android_text_Layout
 * Method:    native_set_ellipsize
 * Signature: (JIF)V
 */
JNIEXPORT void JNICALL Java_android_text_Layout_native_1set_1ellipsize
  (JNIEnv *, jobject, jlong, jint, jfloat);

/*
 * Class:     android_text_Layout
 * Method:    native_get_ellipsis_count
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_android_text_Layout_native_1get_1ellipsis_1count
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     android_text_Layout
 * Method:    native_draw
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_android_text_Layout_native_1draw
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     android_text_Layout
 * Method:    native_draw_custom_canvas
 * Signature: (JLandroid/graphics/Canvas;Landroid/graphics/Paint;)V
 */
JNIEXPORT void JNICALL Java_android_text_Layout_native_1draw_1custom_1canvas
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     android_text_Layout
 * Method:    native_get_line_for_offset
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_android_text_Layout_native_1get_1line_1for_1offset
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     android_text_Layout
 * Method:    native_get_primary_horizontal
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_android_text_Layout_native_1get_1primary_1horizontal
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     android_text_Layout
 * Method:    native_get_secondary_horizontal
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_android_text_Layout_native_1get_1secondary_1horizontal
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     android_text_Layout
 * Method:    native_get_offset_for_horizontal
 * Signature: (JIF)I
 */
JNIEXPORT jint JNICALL Java_android_text_Layout_native_1get_1offset_1for_1horizontal
  (JNIEnv *, jobject, jlong, jint, jfloat);

/*
 * Class:     android_text_Layout
 * Method:    native_get_desired_width
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_android_text_Layout_native_1get_1desired_1width
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_text_Layout
 * Method:    native_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_text_Layout_native_1free
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
