/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_Paint */

#ifndef _Included_android_graphics_Paint
#define _Included_android_graphics_Paint
#ifdef __cplusplus
extern "C" {
#endif
#undef android_graphics_Paint_ANTI_ALIAS_FLAG
#define android_graphics_Paint_ANTI_ALIAS_FLAG 1L
#undef android_graphics_Paint_FILTER_BITMAP_FLAG
#define android_graphics_Paint_FILTER_BITMAP_FLAG 2L
#undef android_graphics_Paint_DITHER_FLAG
#define android_graphics_Paint_DITHER_FLAG 4L
#undef android_graphics_Paint_UNDERLINE_TEXT_FLAG
#define android_graphics_Paint_UNDERLINE_TEXT_FLAG 8L
#undef android_graphics_Paint_STRIKE_THRU_TEXT_FLAG
#define android_graphics_Paint_STRIKE_THRU_TEXT_FLAG 16L
#undef android_graphics_Paint_FAKE_BOLD_TEXT_FLAG
#define android_graphics_Paint_FAKE_BOLD_TEXT_FLAG 32L
#undef android_graphics_Paint_LINEAR_TEXT_FLAG
#define android_graphics_Paint_LINEAR_TEXT_FLAG 64L
#undef android_graphics_Paint_SUBPIXEL_TEXT_FLAG
#define android_graphics_Paint_SUBPIXEL_TEXT_FLAG 128L
#undef android_graphics_Paint_DEV_KERN_TEXT_FLAG
#define android_graphics_Paint_DEV_KERN_TEXT_FLAG 256L
#undef android_graphics_Paint_LCD_RENDER_TEXT_FLAG
#define android_graphics_Paint_LCD_RENDER_TEXT_FLAG 512L
#undef android_graphics_Paint_EMBEDDED_BITMAP_TEXT_FLAG
#define android_graphics_Paint_EMBEDDED_BITMAP_TEXT_FLAG 1024L
#undef android_graphics_Paint_AUTO_HINTING_TEXT_FLAG
#define android_graphics_Paint_AUTO_HINTING_TEXT_FLAG 2048L
#undef android_graphics_Paint_VERTICAL_TEXT_FLAG
#define android_graphics_Paint_VERTICAL_TEXT_FLAG 4096L
/*
 * Class:     android_graphics_Paint
 * Method:    native_create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_Paint_native_1create
  (JNIEnv *, jclass);

/*
 * Class:     android_graphics_Paint
 * Method:    native_clone
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_Paint_native_1clone
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Paint
 * Method:    native_recycle
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Paint_native_1recycle
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Paint
 * Method:    native_set_color
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Paint_native_1set_1color
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_graphics_Paint
 * Method:    native_get_color
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_android_graphics_Paint_native_1get_1color
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Paint
 * Method:    native_set_alpha
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Paint_native_1set_1alpha
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_graphics_Paint
 * Method:    native_get_alpha
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_android_graphics_Paint_native_1get_1alpha
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Paint
 * Method:    native_set_style
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Paint_native_1set_1style
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_graphics_Paint
 * Method:    native_get_style
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_android_graphics_Paint_native_1get_1style
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Paint
 * Method:    native_set_stroke_width
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Paint_native_1set_1stroke_1width
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     android_graphics_Paint
 * Method:    native_get_stroke_width
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_android_graphics_Paint_native_1get_1stroke_1width
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Paint
 * Method:    native_set_stroke_cap
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Paint_native_1set_1stroke_1cap
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_graphics_Paint
 * Method:    native_get_stroke_cap
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_android_graphics_Paint_native_1get_1stroke_1cap
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Paint
 * Method:    native_set_stroke_join
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Paint_native_1set_1stroke_1join
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_graphics_Paint
 * Method:    native_get_stroke_join
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_android_graphics_Paint_native_1get_1stroke_1join
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Paint
 * Method:    native_set_text_size
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Paint_native_1set_1text_1size
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     android_graphics_Paint
 * Method:    native_get_text_size
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_android_graphics_Paint_native_1get_1text_1size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Paint
 * Method:    native_set_color_filter
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Paint_native_1set_1color_1filter
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     android_graphics_Paint
 * Method:    native_get_text_bounds
 * Signature: (JLjava/lang/String;Landroid/graphics/Rect;)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Paint_native_1get_1text_1bounds
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     android_graphics_Paint
 * Method:    native_set_text_align
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Paint_native_1set_1text_1align
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
