/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_content_res_StringBlock */

#ifndef _Included_android_content_res_StringBlock
#define _Included_android_content_res_StringBlock
#ifdef __cplusplus
extern "C" {
#endif
#undef android_content_res_StringBlock_localLOGV
#define android_content_res_StringBlock_localLOGV 0L
/*
 * Class:     android_content_res_StringBlock
 * Method:    nativeCreate
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_android_content_res_StringBlock_nativeCreate
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     android_content_res_StringBlock
 * Method:    nativeGetSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_android_content_res_StringBlock_nativeGetSize
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_content_res_StringBlock
 * Method:    nativeGetString
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_android_content_res_StringBlock_nativeGetString
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_content_res_StringBlock
 * Method:    nativeGetStyle
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_android_content_res_StringBlock_nativeGetStyle
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_content_res_StringBlock
 * Method:    nativeDestroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_android_content_res_StringBlock_nativeDestroy
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
