/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_atl_GskCanvas */

#ifndef _Included_android_atl_GskCanvas
#define _Included_android_atl_GskCanvas
#ifdef __cplusplus
extern "C" {
#endif
#undef android_atl_GskCanvas_HAS_ALPHA_LAYER_SAVE_FLAG
#define android_atl_GskCanvas_HAS_ALPHA_LAYER_SAVE_FLAG 4L
/*
 * Class:     android_atl_GskCanvas
 * Method:    native_drawBitmap
 * Signature: (JJIIIIJ)V
 */
JNIEXPORT void JNICALL Java_android_atl_GskCanvas_native_1drawBitmap__JJIIIIJ
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jint, jint, jlong);

/*
 * Class:     android_atl_GskCanvas
 * Method:    native_drawBitmap
 * Signature: (JJIIIIIIIIJ)V
 */
JNIEXPORT void JNICALL Java_android_atl_GskCanvas_native_1drawBitmap__JJIIIIIIIIJ
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jint, jint, jint, jint, jint, jint, jlong);

/*
 * Class:     android_atl_GskCanvas
 * Method:    native_drawRect
 * Signature: (JFFFFJ)V
 */
JNIEXPORT void JNICALL Java_android_atl_GskCanvas_native_1drawRect
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jlong);

/*
 * Class:     android_atl_GskCanvas
 * Method:    native_drawPath
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_android_atl_GskCanvas_native_1drawPath
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     android_atl_GskCanvas
 * Method:    native_translate
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_android_atl_GskCanvas_native_1translate
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     android_atl_GskCanvas
 * Method:    native_rotate
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_android_atl_GskCanvas_native_1rotate
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     android_atl_GskCanvas
 * Method:    native_save
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_atl_GskCanvas_native_1save
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_atl_GskCanvas
 * Method:    native_restore
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_atl_GskCanvas_native_1restore
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_atl_GskCanvas
 * Method:    native_drawLine
 * Signature: (JFFFFJ)V
 */
JNIEXPORT void JNICALL Java_android_atl_GskCanvas_native_1drawLine
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jlong);

/*
 * Class:     android_atl_GskCanvas
 * Method:    native_drawLines
 * Signature: (J[FIIJ)V
 */
JNIEXPORT void JNICALL Java_android_atl_GskCanvas_native_1drawLines
  (JNIEnv *, jobject, jlong, jfloatArray, jint, jint, jlong);

/*
 * Class:     android_atl_GskCanvas
 * Method:    native_drawText
 * Signature: (JLjava/lang/String;FFJ)V
 */
JNIEXPORT void JNICALL Java_android_atl_GskCanvas_native_1drawText
  (JNIEnv *, jobject, jlong, jstring, jfloat, jfloat, jlong);

/*
 * Class:     android_atl_GskCanvas
 * Method:    native_drawRoundRect
 * Signature: (JFFFFFFJ)V
 */
JNIEXPORT void JNICALL Java_android_atl_GskCanvas_native_1drawRoundRect
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jlong);

/*
 * Class:     android_atl_GskCanvas
 * Method:    native_scale
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_android_atl_GskCanvas_native_1scale
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     android_atl_GskCanvas
 * Method:    native_concat
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_android_atl_GskCanvas_native_1concat
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     android_atl_GskCanvas
 * Method:    native_clipRect
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_android_atl_GskCanvas_native_1clipRect
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_atl_GskCanvas
 * Method:    native_pop
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_android_atl_GskCanvas_native_1pop
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     android_atl_GskCanvas
 * Method:    native_drawRenderNode
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_android_atl_GskCanvas_native_1drawRenderNode
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
