/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_os_Process */

#ifndef _Included_android_os_Process
#define _Included_android_os_Process
#ifdef __cplusplus
extern "C" {
#endif
#undef android_os_Process_SYSTEM_UID
#define android_os_Process_SYSTEM_UID 1000L
#undef android_os_Process_PHONE_UID
#define android_os_Process_PHONE_UID 1001L
#undef android_os_Process_SHELL_UID
#define android_os_Process_SHELL_UID 2000L
#undef android_os_Process_LOG_UID
#define android_os_Process_LOG_UID 1007L
#undef android_os_Process_WIFI_UID
#define android_os_Process_WIFI_UID 1010L
#undef android_os_Process_MEDIA_UID
#define android_os_Process_MEDIA_UID 1013L
#undef android_os_Process_DRM_UID
#define android_os_Process_DRM_UID 1019L
#undef android_os_Process_VPN_UID
#define android_os_Process_VPN_UID 1016L
#undef android_os_Process_NFC_UID
#define android_os_Process_NFC_UID 1027L
#undef android_os_Process_BLUETOOTH_UID
#define android_os_Process_BLUETOOTH_UID 1002L
#undef android_os_Process_MEDIA_RW_GID
#define android_os_Process_MEDIA_RW_GID 1023L
#undef android_os_Process_PACKAGE_INFO_GID
#define android_os_Process_PACKAGE_INFO_GID 1032L
#undef android_os_Process_FIRST_APPLICATION_UID
#define android_os_Process_FIRST_APPLICATION_UID 10000L
#undef android_os_Process_LAST_APPLICATION_UID
#define android_os_Process_LAST_APPLICATION_UID 19999L
#undef android_os_Process_FIRST_ISOLATED_UID
#define android_os_Process_FIRST_ISOLATED_UID 99000L
#undef android_os_Process_LAST_ISOLATED_UID
#define android_os_Process_LAST_ISOLATED_UID 99999L
#undef android_os_Process_FIRST_SHARED_APPLICATION_GID
#define android_os_Process_FIRST_SHARED_APPLICATION_GID 50000L
#undef android_os_Process_LAST_SHARED_APPLICATION_GID
#define android_os_Process_LAST_SHARED_APPLICATION_GID 59999L
#undef android_os_Process_THREAD_PRIORITY_DEFAULT
#define android_os_Process_THREAD_PRIORITY_DEFAULT 0L
#undef android_os_Process_THREAD_PRIORITY_LOWEST
#define android_os_Process_THREAD_PRIORITY_LOWEST 19L
#undef android_os_Process_THREAD_PRIORITY_BACKGROUND
#define android_os_Process_THREAD_PRIORITY_BACKGROUND 10L
#undef android_os_Process_THREAD_PRIORITY_FOREGROUND
#define android_os_Process_THREAD_PRIORITY_FOREGROUND -2L
#undef android_os_Process_THREAD_PRIORITY_DISPLAY
#define android_os_Process_THREAD_PRIORITY_DISPLAY -4L
#undef android_os_Process_THREAD_PRIORITY_URGENT_DISPLAY
#define android_os_Process_THREAD_PRIORITY_URGENT_DISPLAY -8L
#undef android_os_Process_THREAD_PRIORITY_AUDIO
#define android_os_Process_THREAD_PRIORITY_AUDIO -16L
#undef android_os_Process_THREAD_PRIORITY_URGENT_AUDIO
#define android_os_Process_THREAD_PRIORITY_URGENT_AUDIO -19L
#undef android_os_Process_THREAD_PRIORITY_MORE_FAVORABLE
#define android_os_Process_THREAD_PRIORITY_MORE_FAVORABLE -1L
#undef android_os_Process_THREAD_PRIORITY_LESS_FAVORABLE
#define android_os_Process_THREAD_PRIORITY_LESS_FAVORABLE 1L
#undef android_os_Process_SCHED_OTHER
#define android_os_Process_SCHED_OTHER 0L
#undef android_os_Process_SCHED_FIFO
#define android_os_Process_SCHED_FIFO 1L
#undef android_os_Process_SCHED_RR
#define android_os_Process_SCHED_RR 2L
#undef android_os_Process_SCHED_BATCH
#define android_os_Process_SCHED_BATCH 3L
#undef android_os_Process_SCHED_IDLE
#define android_os_Process_SCHED_IDLE 5L
#undef android_os_Process_THREAD_GROUP_DEFAULT
#define android_os_Process_THREAD_GROUP_DEFAULT -1L
#undef android_os_Process_THREAD_GROUP_BG_NONINTERACTIVE
#define android_os_Process_THREAD_GROUP_BG_NONINTERACTIVE 0L
#undef android_os_Process_THREAD_GROUP_FOREGROUND
#define android_os_Process_THREAD_GROUP_FOREGROUND 1L
#undef android_os_Process_THREAD_GROUP_SYSTEM
#define android_os_Process_THREAD_GROUP_SYSTEM 2L
#undef android_os_Process_THREAD_GROUP_AUDIO_APP
#define android_os_Process_THREAD_GROUP_AUDIO_APP 3L
#undef android_os_Process_THREAD_GROUP_AUDIO_SYS
#define android_os_Process_THREAD_GROUP_AUDIO_SYS 4L
#undef android_os_Process_SIGNAL_QUIT
#define android_os_Process_SIGNAL_QUIT 3L
#undef android_os_Process_SIGNAL_KILL
#define android_os_Process_SIGNAL_KILL 9L
#undef android_os_Process_SIGNAL_USR1
#define android_os_Process_SIGNAL_USR1 10L
#undef android_os_Process_ZYGOTE_RETRY_MILLIS
#define android_os_Process_ZYGOTE_RETRY_MILLIS 500L
#undef android_os_Process_PROC_TERM_MASK
#define android_os_Process_PROC_TERM_MASK 255L
#undef android_os_Process_PROC_ZERO_TERM
#define android_os_Process_PROC_ZERO_TERM 0L
#undef android_os_Process_PROC_SPACE_TERM
#define android_os_Process_PROC_SPACE_TERM 32L
#undef android_os_Process_PROC_TAB_TERM
#define android_os_Process_PROC_TAB_TERM 9L
#undef android_os_Process_PROC_COMBINE
#define android_os_Process_PROC_COMBINE 256L
#undef android_os_Process_PROC_PARENS
#define android_os_Process_PROC_PARENS 512L
#undef android_os_Process_PROC_QUOTES
#define android_os_Process_PROC_QUOTES 1024L
#undef android_os_Process_PROC_OUT_STRING
#define android_os_Process_PROC_OUT_STRING 4096L
#undef android_os_Process_PROC_OUT_LONG
#define android_os_Process_PROC_OUT_LONG 8192L
#undef android_os_Process_PROC_OUT_FLOAT
#define android_os_Process_PROC_OUT_FLOAT 16384L
/*
 * Class:     android_os_Process
 * Method:    getElapsedCpuTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_os_Process_getElapsedCpuTime
  (JNIEnv *, jclass);

/*
 * Class:     android_os_Process
 * Method:    getUidForName
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_android_os_Process_getUidForName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     android_os_Process
 * Method:    getGidForName
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_android_os_Process_getGidForName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     android_os_Process
 * Method:    setCanSelfBackground
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_android_os_Process_setCanSelfBackground
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     android_os_Process
 * Method:    setThreadGroup
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_android_os_Process_setThreadGroup
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_os_Process
 * Method:    setProcessGroup
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_android_os_Process_setProcessGroup
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_os_Process
 * Method:    getProcessGroup
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_android_os_Process_getProcessGroup
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_os_Process
 * Method:    getThreadPriority
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_android_os_Process_getThreadPriority
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_os_Process
 * Method:    setThreadScheduler
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_android_os_Process_setThreadScheduler
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     android_os_Process
 * Method:    setOomAdj
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_android_os_Process_setOomAdj
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_os_Process
 * Method:    setSwappiness
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_android_os_Process_setSwappiness
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     android_os_Process
 * Method:    setArgV0
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_os_Process_setArgV0
  (JNIEnv *, jclass, jstring);

/*
 * Class:     android_os_Process
 * Method:    setUid
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_android_os_Process_setUid
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_os_Process
 * Method:    setGid
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_android_os_Process_setGid
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_os_Process
 * Method:    sendSignal
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_android_os_Process_sendSignal
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_os_Process
 * Method:    sendSignalQuiet
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_android_os_Process_sendSignalQuiet
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_os_Process
 * Method:    getFreeMemory
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_os_Process_getFreeMemory
  (JNIEnv *, jclass);

/*
 * Class:     android_os_Process
 * Method:    getTotalMemory
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_os_Process_getTotalMemory
  (JNIEnv *, jclass);

/*
 * Class:     android_os_Process
 * Method:    readProcLines
 * Signature: (Ljava/lang/String;[Ljava/lang/String;[J)V
 */
JNIEXPORT void JNICALL Java_android_os_Process_readProcLines
  (JNIEnv *, jclass, jstring, jobjectArray, jlongArray);

/*
 * Class:     android_os_Process
 * Method:    getPids
 * Signature: (Ljava/lang/String;[I)[I
 */
JNIEXPORT jintArray JNICALL Java_android_os_Process_getPids
  (JNIEnv *, jclass, jstring, jintArray);

/*
 * Class:     android_os_Process
 * Method:    parseProcLine
 * Signature: ([BII[I[Ljava/lang/String;[J[F)Z
 */
JNIEXPORT jboolean JNICALL Java_android_os_Process_parseProcLine
  (JNIEnv *, jclass, jbyteArray, jint, jint, jintArray, jobjectArray, jlongArray, jfloatArray);

/*
 * Class:     android_os_Process
 * Method:    getPidsForCommands
 * Signature: ([Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_android_os_Process_getPidsForCommands
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     android_os_Process
 * Method:    getPss
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_android_os_Process_getPss
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_os_Process
 * Method:    is64Bit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_android_os_Process_is64Bit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
