/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_os_Vibrator */

#ifndef _Included_android_os_Vibrator
#define _Included_android_os_Vibrator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_os_Vibrator
 * Method:    native_vibrate
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_android_os_Vibrator_native_1vibrate
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     android_os_Vibrator
 * Method:    native_constructor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_android_os_Vibrator_native_1constructor
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
