/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_view_ViewTreeObserver */

#ifndef _Included_android_view_ViewTreeObserver
#define _Included_android_view_ViewTreeObserver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_view_ViewTreeObserver
 * Method:    native_set_have_global_layout_listeners
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_android_view_ViewTreeObserver_native_1set_1have_1global_1layout_1listeners
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
