/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_view_inputmethod_InputMethodManager */

#ifndef _Included_android_view_inputmethod_InputMethodManager
#define _Included_android_view_inputmethod_InputMethodManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_view_inputmethod_InputMethodManager
 * Method:    nativeInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_view_inputmethod_InputMethodManager_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     android_view_inputmethod_InputMethodManager
 * Method:    nativeShowSoftInput
 * Signature: (JJLandroid/view/inputmethod/InputConnection;I)Z
 */
JNIEXPORT jboolean JNICALL Java_android_view_inputmethod_InputMethodManager_nativeShowSoftInput
  (JNIEnv *, jobject, jlong, jlong, jobject, jint);

/*
 * Class:     android_view_inputmethod_InputMethodManager
 * Method:    nativeHideSoftInput
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_view_inputmethod_InputMethodManager_nativeHideSoftInput
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
