/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_net_ConnectivityManager */

#ifndef _Included_android_net_ConnectivityManager
#define _Included_android_net_ConnectivityManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_net_ConnectivityManager
 * Method:    registerNetworkCallback
 * Signature: (Landroid/net/NetworkRequest;Landroid/net/ConnectivityManager/NetworkCallback;)V
 */
JNIEXPORT void JNICALL Java_android_net_ConnectivityManager_registerNetworkCallback
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     android_net_ConnectivityManager
 * Method:    isActiveNetworkMetered
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_android_net_ConnectivityManager_isActiveNetworkMetered
  (JNIEnv *, jobject);

/*
 * Class:     android_net_ConnectivityManager
 * Method:    nativeGetNetworkAvailable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_android_net_ConnectivityManager_nativeGetNetworkAvailable
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
