/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_database_sqlite_SQLiteDebug */

#ifndef _Included_android_database_sqlite_SQLiteDebug
#define _Included_android_database_sqlite_SQLiteDebug
#ifdef __cplusplus
extern "C" {
#endif
#undef android_database_sqlite_SQLiteDebug_DEBUG_LOG_SLOW_QUERIES
#define android_database_sqlite_SQLiteDebug_DEBUG_LOG_SLOW_QUERIES 0L
/*
 * Class:     android_database_sqlite_SQLiteDebug
 * Method:    nativeGetPagerStats
 * Signature: (Landroid/database/sqlite/SQLiteDebug/PagerStats;)V
 */
JNIEXPORT void JNICALL Java_android_database_sqlite_SQLiteDebug_nativeGetPagerStats
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
