/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_media_session_MediaSession */

#ifndef _Included_android_media_session_MediaSession
#define _Included_android_media_session_MediaSession
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_media_session_MediaSession
 * Method:    nativeSetState
 * Signature: (IJJJLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_media_session_MediaSession_nativeSetState
  (JNIEnv *, jobject, jint, jlong, jlong, jlong, jstring, jstring, jstring);

/*
 * Class:     android_media_session_MediaSession
 * Method:    nativeSetCallback
 * Signature: (Landroid/media/session/MediaSession/Callback;)V
 */
JNIEXPORT void JNICALL Java_android_media_session_MediaSession_nativeSetCallback
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
