/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_BitmapFactory_Options */

#ifndef _Included_android_graphics_BitmapFactory_Options
#define _Included_android_graphics_BitmapFactory_Options
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_graphics_BitmapFactory_Options
 * Method:    requestCancel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_graphics_BitmapFactory_00024Options_requestCancel
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
