/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_os_Trace */

#ifndef _Included_android_os_Trace
#define _Included_android_os_Trace
#ifdef __cplusplus
extern "C" {
#endif
#undef android_os_Trace_TRACE_TAG_NEVER
#define android_os_Trace_TRACE_TAG_NEVER 0LL
#undef android_os_Trace_TRACE_TAG_ALWAYS
#define android_os_Trace_TRACE_TAG_ALWAYS 1LL
#undef android_os_Trace_TRACE_TAG_GRAPHICS
#define android_os_Trace_TRACE_TAG_GRAPHICS 2LL
#undef android_os_Trace_TRACE_TAG_INPUT
#define android_os_Trace_TRACE_TAG_INPUT 4LL
#undef android_os_Trace_TRACE_TAG_VIEW
#define android_os_Trace_TRACE_TAG_VIEW 8LL
#undef android_os_Trace_TRACE_TAG_WEBVIEW
#define android_os_Trace_TRACE_TAG_WEBVIEW 16LL
#undef android_os_Trace_TRACE_TAG_WINDOW_MANAGER
#define android_os_Trace_TRACE_TAG_WINDOW_MANAGER 32LL
#undef android_os_Trace_TRACE_TAG_ACTIVITY_MANAGER
#define android_os_Trace_TRACE_TAG_ACTIVITY_MANAGER 64LL
#undef android_os_Trace_TRACE_TAG_SYNC_MANAGER
#define android_os_Trace_TRACE_TAG_SYNC_MANAGER 128LL
#undef android_os_Trace_TRACE_TAG_AUDIO
#define android_os_Trace_TRACE_TAG_AUDIO 256LL
#undef android_os_Trace_TRACE_TAG_VIDEO
#define android_os_Trace_TRACE_TAG_VIDEO 512LL
#undef android_os_Trace_TRACE_TAG_CAMERA
#define android_os_Trace_TRACE_TAG_CAMERA 1024LL
#undef android_os_Trace_TRACE_TAG_HAL
#define android_os_Trace_TRACE_TAG_HAL 2048LL
#undef android_os_Trace_TRACE_TAG_APP
#define android_os_Trace_TRACE_TAG_APP 4096LL
#undef android_os_Trace_TRACE_TAG_RESOURCES
#define android_os_Trace_TRACE_TAG_RESOURCES 8192LL
#undef android_os_Trace_TRACE_TAG_DALVIK
#define android_os_Trace_TRACE_TAG_DALVIK 16384LL
#undef android_os_Trace_TRACE_TAG_RS
#define android_os_Trace_TRACE_TAG_RS 32768LL
#undef android_os_Trace_TRACE_TAG_NOT_READY
#define android_os_Trace_TRACE_TAG_NOT_READY -9223372036854775808LL
#undef android_os_Trace_MAX_SECTION_NAME_LEN
#define android_os_Trace_MAX_SECTION_NAME_LEN 127L
/*
 * Class:     android_os_Trace
 * Method:    nativeGetEnabledTags
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_os_Trace_nativeGetEnabledTags
  (JNIEnv *, jclass);

/*
 * Class:     android_os_Trace
 * Method:    nativeTraceCounter
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_android_os_Trace_nativeTraceCounter
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     android_os_Trace
 * Method:    nativeTraceBegin
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_os_Trace_nativeTraceBegin
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     android_os_Trace
 * Method:    nativeTraceEnd
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_os_Trace_nativeTraceEnd
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_os_Trace
 * Method:    nativeAsyncTraceBegin
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_android_os_Trace_nativeAsyncTraceBegin
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     android_os_Trace
 * Method:    nativeAsyncTraceEnd
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_android_os_Trace_nativeAsyncTraceEnd
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     android_os_Trace
 * Method:    nativeSetAppTracingAllowed
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_android_os_Trace_nativeSetAppTracingAllowed
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     android_os_Trace
 * Method:    nativeSetTracingEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_android_os_Trace_nativeSetTracingEnabled
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
