/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_os_Environment */

#ifndef _Included_android_os_Environment
#define _Included_android_os_Environment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_os_Environment
 * Method:    native_get_app_data_dir
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_android_os_Environment_native_1get_1app_1data_1dir
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
