/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_PorterDuffColorFilter */

#ifndef _Included_android_graphics_PorterDuffColorFilter
#define _Included_android_graphics_PorterDuffColorFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_graphics_PorterDuffColorFilter
 * Method:    native_CreatePorterDuffFilter
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_PorterDuffColorFilter_native_1CreatePorterDuffFilter
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
