/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_SweepGradient */

#ifndef _Included_android_graphics_SweepGradient
#define _Included_android_graphics_SweepGradient
#ifdef __cplusplus
extern "C" {
#endif
#undef android_graphics_SweepGradient_TYPE_COLORS_AND_POSITIONS
#define android_graphics_SweepGradient_TYPE_COLORS_AND_POSITIONS 1L
#undef android_graphics_SweepGradient_TYPE_COLOR_START_AND_COLOR_END
#define android_graphics_SweepGradient_TYPE_COLOR_START_AND_COLOR_END 2L
/*
 * Class:     android_graphics_SweepGradient
 * Method:    nativeCreate1
 * Signature: (FF[I[F)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_SweepGradient_nativeCreate1
  (JNIEnv *, jclass, jfloat, jfloat, jintArray, jfloatArray);

/*
 * Class:     android_graphics_SweepGradient
 * Method:    nativeCreate2
 * Signature: (FFII)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_SweepGradient_nativeCreate2
  (JNIEnv *, jclass, jfloat, jfloat, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
