/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_Matrix */

#ifndef _Included_android_graphics_Matrix
#define _Included_android_graphics_Matrix
#ifdef __cplusplus
extern "C" {
#endif
#undef android_graphics_Matrix_MSCALE_X
#define android_graphics_Matrix_MSCALE_X 0L
#undef android_graphics_Matrix_MSKEW_X
#define android_graphics_Matrix_MSKEW_X 1L
#undef android_graphics_Matrix_MTRANS_X
#define android_graphics_Matrix_MTRANS_X 2L
#undef android_graphics_Matrix_MSKEW_Y
#define android_graphics_Matrix_MSKEW_Y 3L
#undef android_graphics_Matrix_MSCALE_Y
#define android_graphics_Matrix_MSCALE_Y 4L
#undef android_graphics_Matrix_MTRANS_Y
#define android_graphics_Matrix_MTRANS_Y 5L
#undef android_graphics_Matrix_MPERSP_0
#define android_graphics_Matrix_MPERSP_0 6L
#undef android_graphics_Matrix_MPERSP_1
#define android_graphics_Matrix_MPERSP_1 7L
#undef android_graphics_Matrix_MPERSP_2
#define android_graphics_Matrix_MPERSP_2 8L
/*
 * Class:     android_graphics_Matrix
 * Method:    native_create
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_Matrix_native_1create
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_isIdentity
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1isIdentity
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_rectStaysRect
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1rectStaysRect
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_reset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Matrix_native_1reset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_set
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Matrix_native_1set
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_setTranslate
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Matrix_native_1setTranslate
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_setScale
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Matrix_native_1setScale__JFFFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_setScale
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Matrix_native_1setScale__JFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_setRotate
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Matrix_native_1setRotate__JFFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_setRotate
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Matrix_native_1setRotate__JF
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_setSinCos
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Matrix_native_1setSinCos__JFFFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_setSinCos
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Matrix_native_1setSinCos__JFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_setSkew
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Matrix_native_1setSkew__JFFFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_setSkew
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Matrix_native_1setSkew__JFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_setConcat
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1setConcat
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_preTranslate
 * Signature: (JFF)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1preTranslate
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_preScale
 * Signature: (JFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1preScale__JFFFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_preScale
 * Signature: (JFF)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1preScale__JFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_preRotate
 * Signature: (JFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1preRotate__JFFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_preRotate
 * Signature: (JF)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1preRotate__JF
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_preSkew
 * Signature: (JFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1preSkew__JFFFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_preSkew
 * Signature: (JFF)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1preSkew__JFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_preConcat
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1preConcat
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_postTranslate
 * Signature: (JFF)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1postTranslate
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_postScale
 * Signature: (JFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1postScale__JFFFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_postScale
 * Signature: (JFF)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1postScale__JFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_postRotate
 * Signature: (JFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1postRotate__JFFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_postRotate
 * Signature: (JF)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1postRotate__JF
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_postSkew
 * Signature: (JFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1postSkew__JFFFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_postSkew
 * Signature: (JFF)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1postSkew__JFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_postConcat
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1postConcat
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_setRectToRect
 * Signature: (JLandroid/graphics/RectF;Landroid/graphics/RectF;I)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1setRectToRect
  (JNIEnv *, jclass, jlong, jobject, jobject, jint);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_setPolyToPoly
 * Signature: (J[FI[FII)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1setPolyToPoly
  (JNIEnv *, jclass, jlong, jfloatArray, jint, jfloatArray, jint, jint);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_invert
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1invert
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_mapPoints
 * Signature: (J[FI[FIIZ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Matrix_native_1mapPoints
  (JNIEnv *, jclass, jlong, jfloatArray, jint, jfloatArray, jint, jint, jboolean);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_mapRect
 * Signature: (JLandroid/graphics/RectF;Landroid/graphics/RectF;)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1mapRect
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_mapRadius
 * Signature: (JF)F
 */
JNIEXPORT jfloat JNICALL Java_android_graphics_Matrix_native_1mapRadius
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_getValues
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Matrix_native_1getValues
  (JNIEnv *, jclass, jlong, jfloatArray);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_setValues
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Matrix_native_1setValues
  (JNIEnv *, jclass, jlong, jfloatArray);

/*
 * Class:     android_graphics_Matrix
 * Method:    native_equals
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Matrix_native_1equals
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     android_graphics_Matrix
 * Method:    finalizer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Matrix_finalizer
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
