/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_view_RenderNode */

#ifndef _Included_android_view_RenderNode
#define _Included_android_view_RenderNode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_view_RenderNode
 * Method:    nativeCreateSnapshot
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_view_RenderNode_nativeCreateSnapshot
  (JNIEnv *, jobject);

/*
 * Class:     android_view_RenderNode
 * Method:    nativeCreateNode
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_android_view_RenderNode_nativeCreateNode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_view_RenderNode
 * Method:    nativePatchNode
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_android_view_RenderNode_nativePatchNode
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     android_view_RenderNode
 * Method:    nativeTransform
 * Signature: (JFFFFFFF)J
 */
JNIEXPORT jlong JNICALL Java_android_view_RenderNode_nativeTransform
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_view_RenderNode
 * Method:    nativeClip
 * Signature: (JFFFF)J
 */
JNIEXPORT jlong JNICALL Java_android_view_RenderNode_nativeClip
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_view_RenderNode
 * Method:    nativeUnref
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_view_RenderNode_nativeUnref
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_view_RenderNode
 * Method:    nativeAddStubNode
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_android_view_RenderNode_nativeAddStubNode
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
