/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_view_KeyCharacterMap */

#ifndef _Included_android_view_KeyCharacterMap
#define _Included_android_view_KeyCharacterMap
#ifdef __cplusplus
extern "C" {
#endif
#undef android_view_KeyCharacterMap_BUILT_IN_KEYBOARD
#define android_view_KeyCharacterMap_BUILT_IN_KEYBOARD 0L
#undef android_view_KeyCharacterMap_VIRTUAL_KEYBOARD
#define android_view_KeyCharacterMap_VIRTUAL_KEYBOARD -1L
#undef android_view_KeyCharacterMap_NUMERIC
#define android_view_KeyCharacterMap_NUMERIC 1L
#undef android_view_KeyCharacterMap_PREDICTIVE
#define android_view_KeyCharacterMap_PREDICTIVE 2L
#undef android_view_KeyCharacterMap_ALPHA
#define android_view_KeyCharacterMap_ALPHA 3L
#undef android_view_KeyCharacterMap_FULL
#define android_view_KeyCharacterMap_FULL 4L
#undef android_view_KeyCharacterMap_SPECIAL_FUNCTION
#define android_view_KeyCharacterMap_SPECIAL_FUNCTION 5L
#undef android_view_KeyCharacterMap_HEX_INPUT
#define android_view_KeyCharacterMap_HEX_INPUT 61184L
#undef android_view_KeyCharacterMap_PICKER_DIALOG_INPUT
#define android_view_KeyCharacterMap_PICKER_DIALOG_INPUT 61185L
#undef android_view_KeyCharacterMap_MODIFIER_BEHAVIOR_CHORDED
#define android_view_KeyCharacterMap_MODIFIER_BEHAVIOR_CHORDED 0L
#undef android_view_KeyCharacterMap_MODIFIER_BEHAVIOR_CHORDED_OR_TOGGLED
#define android_view_KeyCharacterMap_MODIFIER_BEHAVIOR_CHORDED_OR_TOGGLED 1L
#undef android_view_KeyCharacterMap_COMBINING_ACCENT
#define android_view_KeyCharacterMap_COMBINING_ACCENT -2147483648L
#undef android_view_KeyCharacterMap_COMBINING_ACCENT_MASK
#define android_view_KeyCharacterMap_COMBINING_ACCENT_MASK 2147483647L
#undef android_view_KeyCharacterMap_ACCENT_ACUTE
#define android_view_KeyCharacterMap_ACCENT_ACUTE 180L
#undef android_view_KeyCharacterMap_ACCENT_BREVE
#define android_view_KeyCharacterMap_ACCENT_BREVE 728L
#undef android_view_KeyCharacterMap_ACCENT_CARON
#define android_view_KeyCharacterMap_ACCENT_CARON 711L
#undef android_view_KeyCharacterMap_ACCENT_CEDILLA
#define android_view_KeyCharacterMap_ACCENT_CEDILLA 184L
#undef android_view_KeyCharacterMap_ACCENT_CIRCUMFLEX
#define android_view_KeyCharacterMap_ACCENT_CIRCUMFLEX 710L
#undef android_view_KeyCharacterMap_ACCENT_COMMA_ABOVE
#define android_view_KeyCharacterMap_ACCENT_COMMA_ABOVE 8125L
#undef android_view_KeyCharacterMap_ACCENT_COMMA_ABOVE_RIGHT
#define android_view_KeyCharacterMap_ACCENT_COMMA_ABOVE_RIGHT 700L
#undef android_view_KeyCharacterMap_ACCENT_DOT_ABOVE
#define android_view_KeyCharacterMap_ACCENT_DOT_ABOVE 729L
#undef android_view_KeyCharacterMap_ACCENT_DOT_BELOW
#define android_view_KeyCharacterMap_ACCENT_DOT_BELOW 46L
#undef android_view_KeyCharacterMap_ACCENT_DOUBLE_ACUTE
#define android_view_KeyCharacterMap_ACCENT_DOUBLE_ACUTE 733L
#undef android_view_KeyCharacterMap_ACCENT_GRAVE
#define android_view_KeyCharacterMap_ACCENT_GRAVE 715L
#undef android_view_KeyCharacterMap_ACCENT_HOOK_ABOVE
#define android_view_KeyCharacterMap_ACCENT_HOOK_ABOVE 704L
#undef android_view_KeyCharacterMap_ACCENT_HORN
#define android_view_KeyCharacterMap_ACCENT_HORN 39L
#undef android_view_KeyCharacterMap_ACCENT_MACRON
#define android_view_KeyCharacterMap_ACCENT_MACRON 175L
#undef android_view_KeyCharacterMap_ACCENT_MACRON_BELOW
#define android_view_KeyCharacterMap_ACCENT_MACRON_BELOW 717L
#undef android_view_KeyCharacterMap_ACCENT_OGONEK
#define android_view_KeyCharacterMap_ACCENT_OGONEK 731L
#undef android_view_KeyCharacterMap_ACCENT_REVERSED_COMMA_ABOVE
#define android_view_KeyCharacterMap_ACCENT_REVERSED_COMMA_ABOVE 701L
#undef android_view_KeyCharacterMap_ACCENT_RING_ABOVE
#define android_view_KeyCharacterMap_ACCENT_RING_ABOVE 730L
#undef android_view_KeyCharacterMap_ACCENT_STROKE
#define android_view_KeyCharacterMap_ACCENT_STROKE 45L
#undef android_view_KeyCharacterMap_ACCENT_TILDE
#define android_view_KeyCharacterMap_ACCENT_TILDE 732L
#undef android_view_KeyCharacterMap_ACCENT_TURNED_COMMA_ABOVE
#define android_view_KeyCharacterMap_ACCENT_TURNED_COMMA_ABOVE 699L
#undef android_view_KeyCharacterMap_ACCENT_UMLAUT
#define android_view_KeyCharacterMap_ACCENT_UMLAUT 168L
#undef android_view_KeyCharacterMap_ACCENT_VERTICAL_LINE_ABOVE
#define android_view_KeyCharacterMap_ACCENT_VERTICAL_LINE_ABOVE 712L
#undef android_view_KeyCharacterMap_ACCENT_VERTICAL_LINE_BELOW
#define android_view_KeyCharacterMap_ACCENT_VERTICAL_LINE_BELOW 716L
#undef android_view_KeyCharacterMap_ACCENT_GRAVE_LEGACY
#define android_view_KeyCharacterMap_ACCENT_GRAVE_LEGACY 96L
#undef android_view_KeyCharacterMap_ACCENT_CIRCUMFLEX_LEGACY
#define android_view_KeyCharacterMap_ACCENT_CIRCUMFLEX_LEGACY 94L
#undef android_view_KeyCharacterMap_ACCENT_TILDE_LEGACY
#define android_view_KeyCharacterMap_ACCENT_TILDE_LEGACY 126L
#undef android_view_KeyCharacterMap_CHAR_SPACE
#define android_view_KeyCharacterMap_CHAR_SPACE 32L
/*
 * Class:     android_view_KeyCharacterMap
 * Method:    nativeDispose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_android_view_KeyCharacterMap_nativeDispose
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_view_KeyCharacterMap
 * Method:    nativeGetCharacter
 * Signature: (III)C
 */
JNIEXPORT jchar JNICALL Java_android_view_KeyCharacterMap_nativeGetCharacter
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     android_view_KeyCharacterMap
 * Method:    nativeGetFallbackAction
 * Signature: (IIILandroid/view/KeyCharacterMap/FallbackAction;)Z
 */
JNIEXPORT jboolean JNICALL Java_android_view_KeyCharacterMap_nativeGetFallbackAction
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     android_view_KeyCharacterMap
 * Method:    nativeGetNumber
 * Signature: (II)C
 */
JNIEXPORT jchar JNICALL Java_android_view_KeyCharacterMap_nativeGetNumber
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_view_KeyCharacterMap
 * Method:    nativeGetMatch
 * Signature: (II[CI)C
 */
JNIEXPORT jchar JNICALL Java_android_view_KeyCharacterMap_nativeGetMatch
  (JNIEnv *, jclass, jint, jint, jcharArray, jint);

/*
 * Class:     android_view_KeyCharacterMap
 * Method:    nativeGetDisplayLabel
 * Signature: (II)C
 */
JNIEXPORT jchar JNICALL Java_android_view_KeyCharacterMap_nativeGetDisplayLabel
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_view_KeyCharacterMap
 * Method:    nativeGetKeyboardType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_android_view_KeyCharacterMap_nativeGetKeyboardType
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_view_KeyCharacterMap
 * Method:    nativeGetEvents
 * Signature: (I[C)[Landroid/view/KeyEvent;
 */
JNIEXPORT jobjectArray JNICALL Java_android_view_KeyCharacterMap_nativeGetEvents
  (JNIEnv *, jclass, jint, jcharArray);

#ifdef __cplusplus
}
#endif
#endif
