/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_BlendModeColorFilter */

#ifndef _Included_android_graphics_BlendModeColorFilter
#define _Included_android_graphics_BlendModeColorFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_graphics_BlendModeColorFilter
 * Method:    native_CreateBlendModeFilter
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_BlendModeColorFilter_native_1CreateBlendModeFilter
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
