/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_content_Context */

#ifndef _Included_android_content_Context
#define _Included_android_content_Context
#ifdef __cplusplus
extern "C" {
#endif
#undef android_content_Context_MODE_PRIVATE
#define android_content_Context_MODE_PRIVATE 0L
#undef android_content_Context_CONTEXT_INCLUDE_CODE
#define android_content_Context_CONTEXT_INCLUDE_CODE 1L
#undef android_content_Context_CONTEXT_IGNORE_SECURITY
#define android_content_Context_CONTEXT_IGNORE_SECURITY 2L
#undef android_content_Context_CONTEXT_RESTRICTED
#define android_content_Context_CONTEXT_RESTRICTED 4L
#undef android_content_Context_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define android_content_Context_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef android_content_Context_MODE_NO_LOCALIZED_COLLATORS
#define android_content_Context_MODE_NO_LOCALIZED_COLLATORS 16L
/*
 * Class:     android_content_Context
 * Method:    native_get_apk_path
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_android_content_Context_native_1get_1apk_1path
  (JNIEnv *, jclass);

/*
 * Class:     android_content_Context
 * Method:    native_updateConfig
 * Signature: (Landroid/content/res/Configuration;)V
 */
JNIEXPORT void JNICALL Java_android_content_Context_native_1updateConfig
  (JNIEnv *, jclass, jobject);

/*
 * Class:     android_content_Context
 * Method:    nativeOpenFile
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_android_content_Context_nativeOpenFile
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_content_Context
 * Method:    nativeShareFile
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_android_content_Context_nativeShareFile
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     android_content_Context
 * Method:    nativeExportUnifiedPush
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_content_Context_nativeExportUnifiedPush
  (JNIEnv *, jclass, jstring);

/*
 * Class:     android_content_Context
 * Method:    nativeRegisterUnifiedPush
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_content_Context_nativeRegisterUnifiedPush
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     android_content_Context
 * Method:    nativeStartExternalService
 * Signature: (Landroid/content/Intent;)V
 */
JNIEXPORT void JNICALL Java_android_content_Context_nativeStartExternalService
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
