/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_opengl_GLUtils */

#ifndef _Included_android_opengl_GLUtils
#define _Included_android_opengl_GLUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_opengl_GLUtils
 * Method:    native_texImage2D
 * Signature: (IIILandroid/graphics/Bitmap;II)I
 */
JNIEXPORT jint JNICALL Java_android_opengl_GLUtils_native_1texImage2D
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
