/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_drawable_DrawableContainer */

#ifndef _Included_android_graphics_drawable_DrawableContainer
#define _Included_android_graphics_drawable_DrawableContainer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_graphics_drawable_DrawableContainer
 * Method:    native_constructor
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_drawable_DrawableContainer_native_1constructor
  (JNIEnv *, jobject);

/*
 * Class:     android_graphics_drawable_DrawableContainer
 * Method:    native_selectChild
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_drawable_DrawableContainer_native_1selectChild
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
