/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_view_Window */

#ifndef _Included_android_view_Window
#define _Included_android_view_Window
#ifdef __cplusplus
extern "C" {
#endif
#undef android_view_Window_FEATURE_OPTIONS_PANEL
#define android_view_Window_FEATURE_OPTIONS_PANEL 0L
#undef android_view_Window_FEATURE_NO_TITLE
#define android_view_Window_FEATURE_NO_TITLE 1L
/*
 * Class:     android_view_Window
 * Method:    set_widget_as_root
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_android_view_Window_set_1widget_1as_1root
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     android_view_Window
 * Method:    set_title
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_view_Window_set_1title
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     android_view_Window
 * Method:    take_input_queue
 * Signature: (JLandroid/view/InputQueue/Callback;Landroid/view/InputQueue;)V
 */
JNIEXPORT void JNICALL Java_android_view_Window_take_1input_1queue
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     android_view_Window
 * Method:    set_layout
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_android_view_Window_set_1layout
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     android_view_Window
 * Method:    set_jobject
 * Signature: (JLandroid/view/Window;)V
 */
JNIEXPORT void JNICALL Java_android_view_Window_set_1jobject
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     android_view_Window
 * Method:    remove_gtk_background
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_view_Window_remove_1gtk_1background
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_view_Window
 * Method:    set_screen_brightness
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_android_view_Window_set_1screen_1brightness
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
