/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_hardware_SensorManager */

#ifndef _Included_android_hardware_SensorManager
#define _Included_android_hardware_SensorManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_hardware_SensorManager
 * Method:    register_accelerometer_listener_native
 * Signature: (Landroid/hardware/SensorEventListener;Landroid/hardware/Sensor;I)V
 */
JNIEXPORT void JNICALL Java_android_hardware_SensorManager_register_1accelerometer_1listener_1native
  (JNIEnv *, jobject, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
