/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_app_AlertDialog */

#ifndef _Included_android_app_AlertDialog
#define _Included_android_app_AlertDialog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_app_AlertDialog
 * Method:    nativeConstruct
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_android_app_AlertDialog_nativeConstruct
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     android_app_AlertDialog
 * Method:    nativeSetMessage
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_app_AlertDialog_nativeSetMessage
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     android_app_AlertDialog
 * Method:    nativeSetItems
 * Signature: (J[Ljava/lang/String;Landroid/content/DialogInterface/OnClickListener;)V
 */
JNIEXPORT void JNICALL Java_android_app_AlertDialog_nativeSetItems
  (JNIEnv *, jobject, jlong, jobjectArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
