/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_widget_PopupWindow */

#ifndef _Included_android_widget_PopupWindow
#define _Included_android_widget_PopupWindow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_widget_PopupWindow
 * Method:    native_constructor
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_widget_PopupWindow_native_1constructor
  (JNIEnv *, jobject);

/*
 * Class:     android_widget_PopupWindow
 * Method:    native_setContentView
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_android_widget_PopupWindow_native_1setContentView
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     android_widget_PopupWindow
 * Method:    native_showAsDropDown
 * Signature: (JJIII)V
 */
JNIEXPORT void JNICALL Java_android_widget_PopupWindow_native_1showAsDropDown
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jint);

/*
 * Class:     android_widget_PopupWindow
 * Method:    native_isShowing
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_android_widget_PopupWindow_native_1isShowing
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_widget_PopupWindow
 * Method:    native_setTouchable
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_android_widget_PopupWindow_native_1setTouchable
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     android_widget_PopupWindow
 * Method:    native_setTouchModal
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_android_widget_PopupWindow_native_1setTouchModal
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     android_widget_PopupWindow
 * Method:    native_dismiss
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_widget_PopupWindow_native_1dismiss
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_widget_PopupWindow
 * Method:    native_update
 * Signature: (JJIIII)V
 */
JNIEXPORT void JNICALL Java_android_widget_PopupWindow_native_1update
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jint, jint);

/*
 * Class:     android_widget_PopupWindow
 * Method:    setOnDismissListener
 * Signature: (Landroid/widget/PopupWindow/OnDismissListener;)V
 */
JNIEXPORT void JNICALL Java_android_widget_PopupWindow_setOnDismissListener
  (JNIEnv *, jobject, jobject);

/*
 * Class:     android_widget_PopupWindow
 * Method:    native_setWidth
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_android_widget_PopupWindow_native_1setWidth
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     android_widget_PopupWindow
 * Method:    native_setHeight
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_android_widget_PopupWindow_native_1setHeight
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     android_widget_PopupWindow
 * Method:    native_getWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_android_widget_PopupWindow_native_1getWidth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_widget_PopupWindow
 * Method:    native_getHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_android_widget_PopupWindow_native_1getHeight
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_widget_PopupWindow
 * Method:    native_isTouchable
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_android_widget_PopupWindow_native_1isTouchable
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
