/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_opengl_GLES20 */

#ifndef _Included_android_opengl_GLES20
#define _Included_android_opengl_GLES20
#ifdef __cplusplus
extern "C" {
#endif
#undef android_opengl_GLES20_GL_ACTIVE_TEXTURE
#define android_opengl_GLES20_GL_ACTIVE_TEXTURE 34016L
#undef android_opengl_GLES20_GL_DEPTH_BUFFER_BIT
#define android_opengl_GLES20_GL_DEPTH_BUFFER_BIT 256L
#undef android_opengl_GLES20_GL_STENCIL_BUFFER_BIT
#define android_opengl_GLES20_GL_STENCIL_BUFFER_BIT 1024L
#undef android_opengl_GLES20_GL_COLOR_BUFFER_BIT
#define android_opengl_GLES20_GL_COLOR_BUFFER_BIT 16384L
#undef android_opengl_GLES20_GL_FALSE
#define android_opengl_GLES20_GL_FALSE 0L
#undef android_opengl_GLES20_GL_TRUE
#define android_opengl_GLES20_GL_TRUE 1L
#undef android_opengl_GLES20_GL_POINTS
#define android_opengl_GLES20_GL_POINTS 0L
#undef android_opengl_GLES20_GL_LINES
#define android_opengl_GLES20_GL_LINES 1L
#undef android_opengl_GLES20_GL_LINE_LOOP
#define android_opengl_GLES20_GL_LINE_LOOP 2L
#undef android_opengl_GLES20_GL_LINE_STRIP
#define android_opengl_GLES20_GL_LINE_STRIP 3L
#undef android_opengl_GLES20_GL_TRIANGLES
#define android_opengl_GLES20_GL_TRIANGLES 4L
#undef android_opengl_GLES20_GL_TRIANGLE_STRIP
#define android_opengl_GLES20_GL_TRIANGLE_STRIP 5L
#undef android_opengl_GLES20_GL_TRIANGLE_FAN
#define android_opengl_GLES20_GL_TRIANGLE_FAN 6L
#undef android_opengl_GLES20_GL_ZERO
#define android_opengl_GLES20_GL_ZERO 0L
#undef android_opengl_GLES20_GL_ONE
#define android_opengl_GLES20_GL_ONE 1L
#undef android_opengl_GLES20_GL_SRC_COLOR
#define android_opengl_GLES20_GL_SRC_COLOR 768L
#undef android_opengl_GLES20_GL_ONE_MINUS_SRC_COLOR
#define android_opengl_GLES20_GL_ONE_MINUS_SRC_COLOR 769L
#undef android_opengl_GLES20_GL_SRC_ALPHA
#define android_opengl_GLES20_GL_SRC_ALPHA 770L
#undef android_opengl_GLES20_GL_ONE_MINUS_SRC_ALPHA
#define android_opengl_GLES20_GL_ONE_MINUS_SRC_ALPHA 771L
#undef android_opengl_GLES20_GL_DST_ALPHA
#define android_opengl_GLES20_GL_DST_ALPHA 772L
#undef android_opengl_GLES20_GL_ONE_MINUS_DST_ALPHA
#define android_opengl_GLES20_GL_ONE_MINUS_DST_ALPHA 773L
#undef android_opengl_GLES20_GL_DST_COLOR
#define android_opengl_GLES20_GL_DST_COLOR 774L
#undef android_opengl_GLES20_GL_ONE_MINUS_DST_COLOR
#define android_opengl_GLES20_GL_ONE_MINUS_DST_COLOR 775L
#undef android_opengl_GLES20_GL_SRC_ALPHA_SATURATE
#define android_opengl_GLES20_GL_SRC_ALPHA_SATURATE 776L
#undef android_opengl_GLES20_GL_FUNC_ADD
#define android_opengl_GLES20_GL_FUNC_ADD 32774L
#undef android_opengl_GLES20_GL_BLEND_EQUATION
#define android_opengl_GLES20_GL_BLEND_EQUATION 32777L
#undef android_opengl_GLES20_GL_BLEND_EQUATION_RGB
#define android_opengl_GLES20_GL_BLEND_EQUATION_RGB 32777L
#undef android_opengl_GLES20_GL_BLEND_EQUATION_ALPHA
#define android_opengl_GLES20_GL_BLEND_EQUATION_ALPHA 34877L
#undef android_opengl_GLES20_GL_FUNC_SUBTRACT
#define android_opengl_GLES20_GL_FUNC_SUBTRACT 32778L
#undef android_opengl_GLES20_GL_FUNC_REVERSE_SUBTRACT
#define android_opengl_GLES20_GL_FUNC_REVERSE_SUBTRACT 32779L
#undef android_opengl_GLES20_GL_BLEND_DST_RGB
#define android_opengl_GLES20_GL_BLEND_DST_RGB 32968L
#undef android_opengl_GLES20_GL_BLEND_SRC_RGB
#define android_opengl_GLES20_GL_BLEND_SRC_RGB 32969L
#undef android_opengl_GLES20_GL_BLEND_DST_ALPHA
#define android_opengl_GLES20_GL_BLEND_DST_ALPHA 32970L
#undef android_opengl_GLES20_GL_BLEND_SRC_ALPHA
#define android_opengl_GLES20_GL_BLEND_SRC_ALPHA 32971L
#undef android_opengl_GLES20_GL_CONSTANT_COLOR
#define android_opengl_GLES20_GL_CONSTANT_COLOR 32769L
#undef android_opengl_GLES20_GL_ONE_MINUS_CONSTANT_COLOR
#define android_opengl_GLES20_GL_ONE_MINUS_CONSTANT_COLOR 32770L
#undef android_opengl_GLES20_GL_CONSTANT_ALPHA
#define android_opengl_GLES20_GL_CONSTANT_ALPHA 32771L
#undef android_opengl_GLES20_GL_ONE_MINUS_CONSTANT_ALPHA
#define android_opengl_GLES20_GL_ONE_MINUS_CONSTANT_ALPHA 32772L
#undef android_opengl_GLES20_GL_BLEND_COLOR
#define android_opengl_GLES20_GL_BLEND_COLOR 32773L
#undef android_opengl_GLES20_GL_ARRAY_BUFFER
#define android_opengl_GLES20_GL_ARRAY_BUFFER 34962L
#undef android_opengl_GLES20_GL_ELEMENT_ARRAY_BUFFER
#define android_opengl_GLES20_GL_ELEMENT_ARRAY_BUFFER 34963L
#undef android_opengl_GLES20_GL_ARRAY_BUFFER_BINDING
#define android_opengl_GLES20_GL_ARRAY_BUFFER_BINDING 34964L
#undef android_opengl_GLES20_GL_ELEMENT_ARRAY_BUFFER_BINDING
#define android_opengl_GLES20_GL_ELEMENT_ARRAY_BUFFER_BINDING 34965L
#undef android_opengl_GLES20_GL_STREAM_DRAW
#define android_opengl_GLES20_GL_STREAM_DRAW 35040L
#undef android_opengl_GLES20_GL_STATIC_DRAW
#define android_opengl_GLES20_GL_STATIC_DRAW 35044L
#undef android_opengl_GLES20_GL_DYNAMIC_DRAW
#define android_opengl_GLES20_GL_DYNAMIC_DRAW 35048L
#undef android_opengl_GLES20_GL_BUFFER_SIZE
#define android_opengl_GLES20_GL_BUFFER_SIZE 34660L
#undef android_opengl_GLES20_GL_BUFFER_USAGE
#define android_opengl_GLES20_GL_BUFFER_USAGE 34661L
#undef android_opengl_GLES20_GL_CURRENT_VERTEX_ATTRIB
#define android_opengl_GLES20_GL_CURRENT_VERTEX_ATTRIB 34342L
#undef android_opengl_GLES20_GL_FRONT
#define android_opengl_GLES20_GL_FRONT 1028L
#undef android_opengl_GLES20_GL_BACK
#define android_opengl_GLES20_GL_BACK 1029L
#undef android_opengl_GLES20_GL_FRONT_AND_BACK
#define android_opengl_GLES20_GL_FRONT_AND_BACK 1032L
#undef android_opengl_GLES20_GL_TEXTURE_2D
#define android_opengl_GLES20_GL_TEXTURE_2D 3553L
#undef android_opengl_GLES20_GL_CULL_FACE
#define android_opengl_GLES20_GL_CULL_FACE 2884L
#undef android_opengl_GLES20_GL_BLEND
#define android_opengl_GLES20_GL_BLEND 3042L
#undef android_opengl_GLES20_GL_DITHER
#define android_opengl_GLES20_GL_DITHER 3024L
#undef android_opengl_GLES20_GL_STENCIL_TEST
#define android_opengl_GLES20_GL_STENCIL_TEST 2960L
#undef android_opengl_GLES20_GL_DEPTH_TEST
#define android_opengl_GLES20_GL_DEPTH_TEST 2929L
#undef android_opengl_GLES20_GL_SCISSOR_TEST
#define android_opengl_GLES20_GL_SCISSOR_TEST 3089L
#undef android_opengl_GLES20_GL_POLYGON_OFFSET_FILL
#define android_opengl_GLES20_GL_POLYGON_OFFSET_FILL 32823L
#undef android_opengl_GLES20_GL_SAMPLE_ALPHA_TO_COVERAGE
#define android_opengl_GLES20_GL_SAMPLE_ALPHA_TO_COVERAGE 32926L
#undef android_opengl_GLES20_GL_SAMPLE_COVERAGE
#define android_opengl_GLES20_GL_SAMPLE_COVERAGE 32928L
#undef android_opengl_GLES20_GL_NO_ERROR
#define android_opengl_GLES20_GL_NO_ERROR 0L
#undef android_opengl_GLES20_GL_INVALID_ENUM
#define android_opengl_GLES20_GL_INVALID_ENUM 1280L
#undef android_opengl_GLES20_GL_INVALID_VALUE
#define android_opengl_GLES20_GL_INVALID_VALUE 1281L
#undef android_opengl_GLES20_GL_INVALID_OPERATION
#define android_opengl_GLES20_GL_INVALID_OPERATION 1282L
#undef android_opengl_GLES20_GL_OUT_OF_MEMORY
#define android_opengl_GLES20_GL_OUT_OF_MEMORY 1285L
#undef android_opengl_GLES20_GL_CW
#define android_opengl_GLES20_GL_CW 2304L
#undef android_opengl_GLES20_GL_CCW
#define android_opengl_GLES20_GL_CCW 2305L
#undef android_opengl_GLES20_GL_LINE_WIDTH
#define android_opengl_GLES20_GL_LINE_WIDTH 2849L
#undef android_opengl_GLES20_GL_ALIASED_POINT_SIZE_RANGE
#define android_opengl_GLES20_GL_ALIASED_POINT_SIZE_RANGE 33901L
#undef android_opengl_GLES20_GL_ALIASED_LINE_WIDTH_RANGE
#define android_opengl_GLES20_GL_ALIASED_LINE_WIDTH_RANGE 33902L
#undef android_opengl_GLES20_GL_CULL_FACE_MODE
#define android_opengl_GLES20_GL_CULL_FACE_MODE 2885L
#undef android_opengl_GLES20_GL_FRONT_FACE
#define android_opengl_GLES20_GL_FRONT_FACE 2886L
#undef android_opengl_GLES20_GL_DEPTH_RANGE
#define android_opengl_GLES20_GL_DEPTH_RANGE 2928L
#undef android_opengl_GLES20_GL_DEPTH_WRITEMASK
#define android_opengl_GLES20_GL_DEPTH_WRITEMASK 2930L
#undef android_opengl_GLES20_GL_DEPTH_CLEAR_VALUE
#define android_opengl_GLES20_GL_DEPTH_CLEAR_VALUE 2931L
#undef android_opengl_GLES20_GL_DEPTH_FUNC
#define android_opengl_GLES20_GL_DEPTH_FUNC 2932L
#undef android_opengl_GLES20_GL_STENCIL_CLEAR_VALUE
#define android_opengl_GLES20_GL_STENCIL_CLEAR_VALUE 2961L
#undef android_opengl_GLES20_GL_STENCIL_FUNC
#define android_opengl_GLES20_GL_STENCIL_FUNC 2962L
#undef android_opengl_GLES20_GL_STENCIL_FAIL
#define android_opengl_GLES20_GL_STENCIL_FAIL 2964L
#undef android_opengl_GLES20_GL_STENCIL_PASS_DEPTH_FAIL
#define android_opengl_GLES20_GL_STENCIL_PASS_DEPTH_FAIL 2965L
#undef android_opengl_GLES20_GL_STENCIL_PASS_DEPTH_PASS
#define android_opengl_GLES20_GL_STENCIL_PASS_DEPTH_PASS 2966L
#undef android_opengl_GLES20_GL_STENCIL_REF
#define android_opengl_GLES20_GL_STENCIL_REF 2967L
#undef android_opengl_GLES20_GL_STENCIL_VALUE_MASK
#define android_opengl_GLES20_GL_STENCIL_VALUE_MASK 2963L
#undef android_opengl_GLES20_GL_STENCIL_WRITEMASK
#define android_opengl_GLES20_GL_STENCIL_WRITEMASK 2968L
#undef android_opengl_GLES20_GL_STENCIL_BACK_FUNC
#define android_opengl_GLES20_GL_STENCIL_BACK_FUNC 34816L
#undef android_opengl_GLES20_GL_STENCIL_BACK_FAIL
#define android_opengl_GLES20_GL_STENCIL_BACK_FAIL 34817L
#undef android_opengl_GLES20_GL_STENCIL_BACK_PASS_DEPTH_FAIL
#define android_opengl_GLES20_GL_STENCIL_BACK_PASS_DEPTH_FAIL 34818L
#undef android_opengl_GLES20_GL_STENCIL_BACK_PASS_DEPTH_PASS
#define android_opengl_GLES20_GL_STENCIL_BACK_PASS_DEPTH_PASS 34819L
#undef android_opengl_GLES20_GL_STENCIL_BACK_REF
#define android_opengl_GLES20_GL_STENCIL_BACK_REF 36003L
#undef android_opengl_GLES20_GL_STENCIL_BACK_VALUE_MASK
#define android_opengl_GLES20_GL_STENCIL_BACK_VALUE_MASK 36004L
#undef android_opengl_GLES20_GL_STENCIL_BACK_WRITEMASK
#define android_opengl_GLES20_GL_STENCIL_BACK_WRITEMASK 36005L
#undef android_opengl_GLES20_GL_VIEWPORT
#define android_opengl_GLES20_GL_VIEWPORT 2978L
#undef android_opengl_GLES20_GL_SCISSOR_BOX
#define android_opengl_GLES20_GL_SCISSOR_BOX 3088L
#undef android_opengl_GLES20_GL_COLOR_CLEAR_VALUE
#define android_opengl_GLES20_GL_COLOR_CLEAR_VALUE 3106L
#undef android_opengl_GLES20_GL_COLOR_WRITEMASK
#define android_opengl_GLES20_GL_COLOR_WRITEMASK 3107L
#undef android_opengl_GLES20_GL_UNPACK_ALIGNMENT
#define android_opengl_GLES20_GL_UNPACK_ALIGNMENT 3317L
#undef android_opengl_GLES20_GL_PACK_ALIGNMENT
#define android_opengl_GLES20_GL_PACK_ALIGNMENT 3333L
#undef android_opengl_GLES20_GL_MAX_TEXTURE_SIZE
#define android_opengl_GLES20_GL_MAX_TEXTURE_SIZE 3379L
#undef android_opengl_GLES20_GL_MAX_VIEWPORT_DIMS
#define android_opengl_GLES20_GL_MAX_VIEWPORT_DIMS 3386L
#undef android_opengl_GLES20_GL_SUBPIXEL_BITS
#define android_opengl_GLES20_GL_SUBPIXEL_BITS 3408L
#undef android_opengl_GLES20_GL_RED_BITS
#define android_opengl_GLES20_GL_RED_BITS 3410L
#undef android_opengl_GLES20_GL_GREEN_BITS
#define android_opengl_GLES20_GL_GREEN_BITS 3411L
#undef android_opengl_GLES20_GL_BLUE_BITS
#define android_opengl_GLES20_GL_BLUE_BITS 3412L
#undef android_opengl_GLES20_GL_ALPHA_BITS
#define android_opengl_GLES20_GL_ALPHA_BITS 3413L
#undef android_opengl_GLES20_GL_DEPTH_BITS
#define android_opengl_GLES20_GL_DEPTH_BITS 3414L
#undef android_opengl_GLES20_GL_STENCIL_BITS
#define android_opengl_GLES20_GL_STENCIL_BITS 3415L
#undef android_opengl_GLES20_GL_POLYGON_OFFSET_UNITS
#define android_opengl_GLES20_GL_POLYGON_OFFSET_UNITS 10752L
#undef android_opengl_GLES20_GL_POLYGON_OFFSET_FACTOR
#define android_opengl_GLES20_GL_POLYGON_OFFSET_FACTOR 32824L
#undef android_opengl_GLES20_GL_TEXTURE_BINDING_2D
#define android_opengl_GLES20_GL_TEXTURE_BINDING_2D 32873L
#undef android_opengl_GLES20_GL_SAMPLE_BUFFERS
#define android_opengl_GLES20_GL_SAMPLE_BUFFERS 32936L
#undef android_opengl_GLES20_GL_SAMPLES
#define android_opengl_GLES20_GL_SAMPLES 32937L
#undef android_opengl_GLES20_GL_SAMPLE_COVERAGE_VALUE
#define android_opengl_GLES20_GL_SAMPLE_COVERAGE_VALUE 32938L
#undef android_opengl_GLES20_GL_SAMPLE_COVERAGE_INVERT
#define android_opengl_GLES20_GL_SAMPLE_COVERAGE_INVERT 32939L
#undef android_opengl_GLES20_GL_NUM_COMPRESSED_TEXTURE_FORMATS
#define android_opengl_GLES20_GL_NUM_COMPRESSED_TEXTURE_FORMATS 34466L
#undef android_opengl_GLES20_GL_COMPRESSED_TEXTURE_FORMATS
#define android_opengl_GLES20_GL_COMPRESSED_TEXTURE_FORMATS 34467L
#undef android_opengl_GLES20_GL_DONT_CARE
#define android_opengl_GLES20_GL_DONT_CARE 4352L
#undef android_opengl_GLES20_GL_FASTEST
#define android_opengl_GLES20_GL_FASTEST 4353L
#undef android_opengl_GLES20_GL_NICEST
#define android_opengl_GLES20_GL_NICEST 4354L
#undef android_opengl_GLES20_GL_GENERATE_MIPMAP_HINT
#define android_opengl_GLES20_GL_GENERATE_MIPMAP_HINT 33170L
#undef android_opengl_GLES20_GL_BYTE
#define android_opengl_GLES20_GL_BYTE 5120L
#undef android_opengl_GLES20_GL_UNSIGNED_BYTE
#define android_opengl_GLES20_GL_UNSIGNED_BYTE 5121L
#undef android_opengl_GLES20_GL_SHORT
#define android_opengl_GLES20_GL_SHORT 5122L
#undef android_opengl_GLES20_GL_UNSIGNED_SHORT
#define android_opengl_GLES20_GL_UNSIGNED_SHORT 5123L
#undef android_opengl_GLES20_GL_INT
#define android_opengl_GLES20_GL_INT 5124L
#undef android_opengl_GLES20_GL_UNSIGNED_INT
#define android_opengl_GLES20_GL_UNSIGNED_INT 5125L
#undef android_opengl_GLES20_GL_FLOAT
#define android_opengl_GLES20_GL_FLOAT 5126L
#undef android_opengl_GLES20_GL_FIXED
#define android_opengl_GLES20_GL_FIXED 5132L
#undef android_opengl_GLES20_GL_DEPTH_COMPONENT
#define android_opengl_GLES20_GL_DEPTH_COMPONENT 6402L
#undef android_opengl_GLES20_GL_ALPHA
#define android_opengl_GLES20_GL_ALPHA 6406L
#undef android_opengl_GLES20_GL_RGB
#define android_opengl_GLES20_GL_RGB 6407L
#undef android_opengl_GLES20_GL_RGBA
#define android_opengl_GLES20_GL_RGBA 6408L
#undef android_opengl_GLES20_GL_LUMINANCE
#define android_opengl_GLES20_GL_LUMINANCE 6409L
#undef android_opengl_GLES20_GL_LUMINANCE_ALPHA
#define android_opengl_GLES20_GL_LUMINANCE_ALPHA 6410L
#undef android_opengl_GLES20_GL_UNSIGNED_SHORT_4_4_4_4
#define android_opengl_GLES20_GL_UNSIGNED_SHORT_4_4_4_4 32819L
#undef android_opengl_GLES20_GL_UNSIGNED_SHORT_5_5_5_1
#define android_opengl_GLES20_GL_UNSIGNED_SHORT_5_5_5_1 32820L
#undef android_opengl_GLES20_GL_UNSIGNED_SHORT_5_6_5
#define android_opengl_GLES20_GL_UNSIGNED_SHORT_5_6_5 33635L
#undef android_opengl_GLES20_GL_FRAGMENT_SHADER
#define android_opengl_GLES20_GL_FRAGMENT_SHADER 35632L
#undef android_opengl_GLES20_GL_VERTEX_SHADER
#define android_opengl_GLES20_GL_VERTEX_SHADER 35633L
#undef android_opengl_GLES20_GL_MAX_VERTEX_ATTRIBS
#define android_opengl_GLES20_GL_MAX_VERTEX_ATTRIBS 34921L
#undef android_opengl_GLES20_GL_MAX_VERTEX_UNIFORM_VECTORS
#define android_opengl_GLES20_GL_MAX_VERTEX_UNIFORM_VECTORS 36347L
#undef android_opengl_GLES20_GL_MAX_VARYING_VECTORS
#define android_opengl_GLES20_GL_MAX_VARYING_VECTORS 36348L
#undef android_opengl_GLES20_GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS
#define android_opengl_GLES20_GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS 35661L
#undef android_opengl_GLES20_GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS
#define android_opengl_GLES20_GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS 35660L
#undef android_opengl_GLES20_GL_MAX_TEXTURE_IMAGE_UNITS
#define android_opengl_GLES20_GL_MAX_TEXTURE_IMAGE_UNITS 34930L
#undef android_opengl_GLES20_GL_MAX_FRAGMENT_UNIFORM_VECTORS
#define android_opengl_GLES20_GL_MAX_FRAGMENT_UNIFORM_VECTORS 36349L
#undef android_opengl_GLES20_GL_SHADER_TYPE
#define android_opengl_GLES20_GL_SHADER_TYPE 35663L
#undef android_opengl_GLES20_GL_DELETE_STATUS
#define android_opengl_GLES20_GL_DELETE_STATUS 35712L
#undef android_opengl_GLES20_GL_LINK_STATUS
#define android_opengl_GLES20_GL_LINK_STATUS 35714L
#undef android_opengl_GLES20_GL_VALIDATE_STATUS
#define android_opengl_GLES20_GL_VALIDATE_STATUS 35715L
#undef android_opengl_GLES20_GL_ATTACHED_SHADERS
#define android_opengl_GLES20_GL_ATTACHED_SHADERS 35717L
#undef android_opengl_GLES20_GL_ACTIVE_UNIFORMS
#define android_opengl_GLES20_GL_ACTIVE_UNIFORMS 35718L
#undef android_opengl_GLES20_GL_ACTIVE_UNIFORM_MAX_LENGTH
#define android_opengl_GLES20_GL_ACTIVE_UNIFORM_MAX_LENGTH 35719L
#undef android_opengl_GLES20_GL_ACTIVE_ATTRIBUTES
#define android_opengl_GLES20_GL_ACTIVE_ATTRIBUTES 35721L
#undef android_opengl_GLES20_GL_ACTIVE_ATTRIBUTE_MAX_LENGTH
#define android_opengl_GLES20_GL_ACTIVE_ATTRIBUTE_MAX_LENGTH 35722L
#undef android_opengl_GLES20_GL_SHADING_LANGUAGE_VERSION
#define android_opengl_GLES20_GL_SHADING_LANGUAGE_VERSION 35724L
#undef android_opengl_GLES20_GL_CURRENT_PROGRAM
#define android_opengl_GLES20_GL_CURRENT_PROGRAM 35725L
#undef android_opengl_GLES20_GL_NEVER
#define android_opengl_GLES20_GL_NEVER 512L
#undef android_opengl_GLES20_GL_LESS
#define android_opengl_GLES20_GL_LESS 513L
#undef android_opengl_GLES20_GL_EQUAL
#define android_opengl_GLES20_GL_EQUAL 514L
#undef android_opengl_GLES20_GL_LEQUAL
#define android_opengl_GLES20_GL_LEQUAL 515L
#undef android_opengl_GLES20_GL_GREATER
#define android_opengl_GLES20_GL_GREATER 516L
#undef android_opengl_GLES20_GL_NOTEQUAL
#define android_opengl_GLES20_GL_NOTEQUAL 517L
#undef android_opengl_GLES20_GL_GEQUAL
#define android_opengl_GLES20_GL_GEQUAL 518L
#undef android_opengl_GLES20_GL_ALWAYS
#define android_opengl_GLES20_GL_ALWAYS 519L
#undef android_opengl_GLES20_GL_KEEP
#define android_opengl_GLES20_GL_KEEP 7680L
#undef android_opengl_GLES20_GL_REPLACE
#define android_opengl_GLES20_GL_REPLACE 7681L
#undef android_opengl_GLES20_GL_INCR
#define android_opengl_GLES20_GL_INCR 7682L
#undef android_opengl_GLES20_GL_DECR
#define android_opengl_GLES20_GL_DECR 7683L
#undef android_opengl_GLES20_GL_INVERT
#define android_opengl_GLES20_GL_INVERT 5386L
#undef android_opengl_GLES20_GL_INCR_WRAP
#define android_opengl_GLES20_GL_INCR_WRAP 34055L
#undef android_opengl_GLES20_GL_DECR_WRAP
#define android_opengl_GLES20_GL_DECR_WRAP 34056L
#undef android_opengl_GLES20_GL_VENDOR
#define android_opengl_GLES20_GL_VENDOR 7936L
#undef android_opengl_GLES20_GL_RENDERER
#define android_opengl_GLES20_GL_RENDERER 7937L
#undef android_opengl_GLES20_GL_VERSION
#define android_opengl_GLES20_GL_VERSION 7938L
#undef android_opengl_GLES20_GL_EXTENSIONS
#define android_opengl_GLES20_GL_EXTENSIONS 7939L
#undef android_opengl_GLES20_GL_NEAREST
#define android_opengl_GLES20_GL_NEAREST 9728L
#undef android_opengl_GLES20_GL_LINEAR
#define android_opengl_GLES20_GL_LINEAR 9729L
#undef android_opengl_GLES20_GL_NEAREST_MIPMAP_NEAREST
#define android_opengl_GLES20_GL_NEAREST_MIPMAP_NEAREST 9984L
#undef android_opengl_GLES20_GL_LINEAR_MIPMAP_NEAREST
#define android_opengl_GLES20_GL_LINEAR_MIPMAP_NEAREST 9985L
#undef android_opengl_GLES20_GL_NEAREST_MIPMAP_LINEAR
#define android_opengl_GLES20_GL_NEAREST_MIPMAP_LINEAR 9986L
#undef android_opengl_GLES20_GL_LINEAR_MIPMAP_LINEAR
#define android_opengl_GLES20_GL_LINEAR_MIPMAP_LINEAR 9987L
#undef android_opengl_GLES20_GL_TEXTURE_MAG_FILTER
#define android_opengl_GLES20_GL_TEXTURE_MAG_FILTER 10240L
#undef android_opengl_GLES20_GL_TEXTURE_MIN_FILTER
#define android_opengl_GLES20_GL_TEXTURE_MIN_FILTER 10241L
#undef android_opengl_GLES20_GL_TEXTURE_WRAP_S
#define android_opengl_GLES20_GL_TEXTURE_WRAP_S 10242L
#undef android_opengl_GLES20_GL_TEXTURE_WRAP_T
#define android_opengl_GLES20_GL_TEXTURE_WRAP_T 10243L
#undef android_opengl_GLES20_GL_TEXTURE
#define android_opengl_GLES20_GL_TEXTURE 5890L
#undef android_opengl_GLES20_GL_TEXTURE_CUBE_MAP
#define android_opengl_GLES20_GL_TEXTURE_CUBE_MAP 34067L
#undef android_opengl_GLES20_GL_TEXTURE_BINDING_CUBE_MAP
#define android_opengl_GLES20_GL_TEXTURE_BINDING_CUBE_MAP 34068L
#undef android_opengl_GLES20_GL_TEXTURE_CUBE_MAP_POSITIVE_X
#define android_opengl_GLES20_GL_TEXTURE_CUBE_MAP_POSITIVE_X 34069L
#undef android_opengl_GLES20_GL_TEXTURE_CUBE_MAP_NEGATIVE_X
#define android_opengl_GLES20_GL_TEXTURE_CUBE_MAP_NEGATIVE_X 34070L
#undef android_opengl_GLES20_GL_TEXTURE_CUBE_MAP_POSITIVE_Y
#define android_opengl_GLES20_GL_TEXTURE_CUBE_MAP_POSITIVE_Y 34071L
#undef android_opengl_GLES20_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y
#define android_opengl_GLES20_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y 34072L
#undef android_opengl_GLES20_GL_TEXTURE_CUBE_MAP_POSITIVE_Z
#define android_opengl_GLES20_GL_TEXTURE_CUBE_MAP_POSITIVE_Z 34073L
#undef android_opengl_GLES20_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z
#define android_opengl_GLES20_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z 34074L
#undef android_opengl_GLES20_GL_MAX_CUBE_MAP_TEXTURE_SIZE
#define android_opengl_GLES20_GL_MAX_CUBE_MAP_TEXTURE_SIZE 34076L
#undef android_opengl_GLES20_GL_TEXTURE0
#define android_opengl_GLES20_GL_TEXTURE0 33984L
#undef android_opengl_GLES20_GL_TEXTURE1
#define android_opengl_GLES20_GL_TEXTURE1 33985L
#undef android_opengl_GLES20_GL_TEXTURE2
#define android_opengl_GLES20_GL_TEXTURE2 33986L
#undef android_opengl_GLES20_GL_TEXTURE3
#define android_opengl_GLES20_GL_TEXTURE3 33987L
#undef android_opengl_GLES20_GL_TEXTURE4
#define android_opengl_GLES20_GL_TEXTURE4 33988L
#undef android_opengl_GLES20_GL_TEXTURE5
#define android_opengl_GLES20_GL_TEXTURE5 33989L
#undef android_opengl_GLES20_GL_TEXTURE6
#define android_opengl_GLES20_GL_TEXTURE6 33990L
#undef android_opengl_GLES20_GL_TEXTURE7
#define android_opengl_GLES20_GL_TEXTURE7 33991L
#undef android_opengl_GLES20_GL_TEXTURE8
#define android_opengl_GLES20_GL_TEXTURE8 33992L
#undef android_opengl_GLES20_GL_TEXTURE9
#define android_opengl_GLES20_GL_TEXTURE9 33993L
#undef android_opengl_GLES20_GL_TEXTURE10
#define android_opengl_GLES20_GL_TEXTURE10 33994L
#undef android_opengl_GLES20_GL_TEXTURE11
#define android_opengl_GLES20_GL_TEXTURE11 33995L
#undef android_opengl_GLES20_GL_TEXTURE12
#define android_opengl_GLES20_GL_TEXTURE12 33996L
#undef android_opengl_GLES20_GL_TEXTURE13
#define android_opengl_GLES20_GL_TEXTURE13 33997L
#undef android_opengl_GLES20_GL_TEXTURE14
#define android_opengl_GLES20_GL_TEXTURE14 33998L
#undef android_opengl_GLES20_GL_TEXTURE15
#define android_opengl_GLES20_GL_TEXTURE15 33999L
#undef android_opengl_GLES20_GL_TEXTURE16
#define android_opengl_GLES20_GL_TEXTURE16 34000L
#undef android_opengl_GLES20_GL_TEXTURE17
#define android_opengl_GLES20_GL_TEXTURE17 34001L
#undef android_opengl_GLES20_GL_TEXTURE18
#define android_opengl_GLES20_GL_TEXTURE18 34002L
#undef android_opengl_GLES20_GL_TEXTURE19
#define android_opengl_GLES20_GL_TEXTURE19 34003L
#undef android_opengl_GLES20_GL_TEXTURE20
#define android_opengl_GLES20_GL_TEXTURE20 34004L
#undef android_opengl_GLES20_GL_TEXTURE21
#define android_opengl_GLES20_GL_TEXTURE21 34005L
#undef android_opengl_GLES20_GL_TEXTURE22
#define android_opengl_GLES20_GL_TEXTURE22 34006L
#undef android_opengl_GLES20_GL_TEXTURE23
#define android_opengl_GLES20_GL_TEXTURE23 34007L
#undef android_opengl_GLES20_GL_TEXTURE24
#define android_opengl_GLES20_GL_TEXTURE24 34008L
#undef android_opengl_GLES20_GL_TEXTURE25
#define android_opengl_GLES20_GL_TEXTURE25 34009L
#undef android_opengl_GLES20_GL_TEXTURE26
#define android_opengl_GLES20_GL_TEXTURE26 34010L
#undef android_opengl_GLES20_GL_TEXTURE27
#define android_opengl_GLES20_GL_TEXTURE27 34011L
#undef android_opengl_GLES20_GL_TEXTURE28
#define android_opengl_GLES20_GL_TEXTURE28 34012L
#undef android_opengl_GLES20_GL_TEXTURE29
#define android_opengl_GLES20_GL_TEXTURE29 34013L
#undef android_opengl_GLES20_GL_TEXTURE30
#define android_opengl_GLES20_GL_TEXTURE30 34014L
#undef android_opengl_GLES20_GL_TEXTURE31
#define android_opengl_GLES20_GL_TEXTURE31 34015L
#undef android_opengl_GLES20_GL_REPEAT
#define android_opengl_GLES20_GL_REPEAT 10497L
#undef android_opengl_GLES20_GL_CLAMP_TO_EDGE
#define android_opengl_GLES20_GL_CLAMP_TO_EDGE 33071L
#undef android_opengl_GLES20_GL_MIRRORED_REPEAT
#define android_opengl_GLES20_GL_MIRRORED_REPEAT 33648L
#undef android_opengl_GLES20_GL_FLOAT_VEC2
#define android_opengl_GLES20_GL_FLOAT_VEC2 35664L
#undef android_opengl_GLES20_GL_FLOAT_VEC3
#define android_opengl_GLES20_GL_FLOAT_VEC3 35665L
#undef android_opengl_GLES20_GL_FLOAT_VEC4
#define android_opengl_GLES20_GL_FLOAT_VEC4 35666L
#undef android_opengl_GLES20_GL_INT_VEC2
#define android_opengl_GLES20_GL_INT_VEC2 35667L
#undef android_opengl_GLES20_GL_INT_VEC3
#define android_opengl_GLES20_GL_INT_VEC3 35668L
#undef android_opengl_GLES20_GL_INT_VEC4
#define android_opengl_GLES20_GL_INT_VEC4 35669L
#undef android_opengl_GLES20_GL_BOOL
#define android_opengl_GLES20_GL_BOOL 35670L
#undef android_opengl_GLES20_GL_BOOL_VEC2
#define android_opengl_GLES20_GL_BOOL_VEC2 35671L
#undef android_opengl_GLES20_GL_BOOL_VEC3
#define android_opengl_GLES20_GL_BOOL_VEC3 35672L
#undef android_opengl_GLES20_GL_BOOL_VEC4
#define android_opengl_GLES20_GL_BOOL_VEC4 35673L
#undef android_opengl_GLES20_GL_FLOAT_MAT2
#define android_opengl_GLES20_GL_FLOAT_MAT2 35674L
#undef android_opengl_GLES20_GL_FLOAT_MAT3
#define android_opengl_GLES20_GL_FLOAT_MAT3 35675L
#undef android_opengl_GLES20_GL_FLOAT_MAT4
#define android_opengl_GLES20_GL_FLOAT_MAT4 35676L
#undef android_opengl_GLES20_GL_SAMPLER_2D
#define android_opengl_GLES20_GL_SAMPLER_2D 35678L
#undef android_opengl_GLES20_GL_SAMPLER_CUBE
#define android_opengl_GLES20_GL_SAMPLER_CUBE 35680L
#undef android_opengl_GLES20_GL_VERTEX_ATTRIB_ARRAY_ENABLED
#define android_opengl_GLES20_GL_VERTEX_ATTRIB_ARRAY_ENABLED 34338L
#undef android_opengl_GLES20_GL_VERTEX_ATTRIB_ARRAY_SIZE
#define android_opengl_GLES20_GL_VERTEX_ATTRIB_ARRAY_SIZE 34339L
#undef android_opengl_GLES20_GL_VERTEX_ATTRIB_ARRAY_STRIDE
#define android_opengl_GLES20_GL_VERTEX_ATTRIB_ARRAY_STRIDE 34340L
#undef android_opengl_GLES20_GL_VERTEX_ATTRIB_ARRAY_TYPE
#define android_opengl_GLES20_GL_VERTEX_ATTRIB_ARRAY_TYPE 34341L
#undef android_opengl_GLES20_GL_VERTEX_ATTRIB_ARRAY_NORMALIZED
#define android_opengl_GLES20_GL_VERTEX_ATTRIB_ARRAY_NORMALIZED 34922L
#undef android_opengl_GLES20_GL_VERTEX_ATTRIB_ARRAY_POINTER
#define android_opengl_GLES20_GL_VERTEX_ATTRIB_ARRAY_POINTER 34373L
#undef android_opengl_GLES20_GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING
#define android_opengl_GLES20_GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING 34975L
#undef android_opengl_GLES20_GL_IMPLEMENTATION_COLOR_READ_TYPE
#define android_opengl_GLES20_GL_IMPLEMENTATION_COLOR_READ_TYPE 35738L
#undef android_opengl_GLES20_GL_IMPLEMENTATION_COLOR_READ_FORMAT
#define android_opengl_GLES20_GL_IMPLEMENTATION_COLOR_READ_FORMAT 35739L
#undef android_opengl_GLES20_GL_COMPILE_STATUS
#define android_opengl_GLES20_GL_COMPILE_STATUS 35713L
#undef android_opengl_GLES20_GL_INFO_LOG_LENGTH
#define android_opengl_GLES20_GL_INFO_LOG_LENGTH 35716L
#undef android_opengl_GLES20_GL_SHADER_SOURCE_LENGTH
#define android_opengl_GLES20_GL_SHADER_SOURCE_LENGTH 35720L
#undef android_opengl_GLES20_GL_SHADER_COMPILER
#define android_opengl_GLES20_GL_SHADER_COMPILER 36346L
#undef android_opengl_GLES20_GL_SHADER_BINARY_FORMATS
#define android_opengl_GLES20_GL_SHADER_BINARY_FORMATS 36344L
#undef android_opengl_GLES20_GL_NUM_SHADER_BINARY_FORMATS
#define android_opengl_GLES20_GL_NUM_SHADER_BINARY_FORMATS 36345L
#undef android_opengl_GLES20_GL_LOW_FLOAT
#define android_opengl_GLES20_GL_LOW_FLOAT 36336L
#undef android_opengl_GLES20_GL_MEDIUM_FLOAT
#define android_opengl_GLES20_GL_MEDIUM_FLOAT 36337L
#undef android_opengl_GLES20_GL_HIGH_FLOAT
#define android_opengl_GLES20_GL_HIGH_FLOAT 36338L
#undef android_opengl_GLES20_GL_LOW_INT
#define android_opengl_GLES20_GL_LOW_INT 36339L
#undef android_opengl_GLES20_GL_MEDIUM_INT
#define android_opengl_GLES20_GL_MEDIUM_INT 36340L
#undef android_opengl_GLES20_GL_HIGH_INT
#define android_opengl_GLES20_GL_HIGH_INT 36341L
#undef android_opengl_GLES20_GL_FRAMEBUFFER
#define android_opengl_GLES20_GL_FRAMEBUFFER 36160L
#undef android_opengl_GLES20_GL_RENDERBUFFER
#define android_opengl_GLES20_GL_RENDERBUFFER 36161L
#undef android_opengl_GLES20_GL_RGBA4
#define android_opengl_GLES20_GL_RGBA4 32854L
#undef android_opengl_GLES20_GL_RGB5_A1
#define android_opengl_GLES20_GL_RGB5_A1 32855L
#undef android_opengl_GLES20_GL_RGB565
#define android_opengl_GLES20_GL_RGB565 36194L
#undef android_opengl_GLES20_GL_DEPTH_COMPONENT16
#define android_opengl_GLES20_GL_DEPTH_COMPONENT16 33189L
#undef android_opengl_GLES20_GL_STENCIL_INDEX
#define android_opengl_GLES20_GL_STENCIL_INDEX 6401L
#undef android_opengl_GLES20_GL_STENCIL_INDEX8
#define android_opengl_GLES20_GL_STENCIL_INDEX8 36168L
#undef android_opengl_GLES20_GL_RENDERBUFFER_WIDTH
#define android_opengl_GLES20_GL_RENDERBUFFER_WIDTH 36162L
#undef android_opengl_GLES20_GL_RENDERBUFFER_HEIGHT
#define android_opengl_GLES20_GL_RENDERBUFFER_HEIGHT 36163L
#undef android_opengl_GLES20_GL_RENDERBUFFER_INTERNAL_FORMAT
#define android_opengl_GLES20_GL_RENDERBUFFER_INTERNAL_FORMAT 36164L
#undef android_opengl_GLES20_GL_RENDERBUFFER_RED_SIZE
#define android_opengl_GLES20_GL_RENDERBUFFER_RED_SIZE 36176L
#undef android_opengl_GLES20_GL_RENDERBUFFER_GREEN_SIZE
#define android_opengl_GLES20_GL_RENDERBUFFER_GREEN_SIZE 36177L
#undef android_opengl_GLES20_GL_RENDERBUFFER_BLUE_SIZE
#define android_opengl_GLES20_GL_RENDERBUFFER_BLUE_SIZE 36178L
#undef android_opengl_GLES20_GL_RENDERBUFFER_ALPHA_SIZE
#define android_opengl_GLES20_GL_RENDERBUFFER_ALPHA_SIZE 36179L
#undef android_opengl_GLES20_GL_RENDERBUFFER_DEPTH_SIZE
#define android_opengl_GLES20_GL_RENDERBUFFER_DEPTH_SIZE 36180L
#undef android_opengl_GLES20_GL_RENDERBUFFER_STENCIL_SIZE
#define android_opengl_GLES20_GL_RENDERBUFFER_STENCIL_SIZE 36181L
#undef android_opengl_GLES20_GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE
#define android_opengl_GLES20_GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE 36048L
#undef android_opengl_GLES20_GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME
#define android_opengl_GLES20_GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME 36049L
#undef android_opengl_GLES20_GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL
#define android_opengl_GLES20_GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL 36050L
#undef android_opengl_GLES20_GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE
#define android_opengl_GLES20_GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE 36051L
#undef android_opengl_GLES20_GL_COLOR_ATTACHMENT0
#define android_opengl_GLES20_GL_COLOR_ATTACHMENT0 36064L
#undef android_opengl_GLES20_GL_DEPTH_ATTACHMENT
#define android_opengl_GLES20_GL_DEPTH_ATTACHMENT 36096L
#undef android_opengl_GLES20_GL_STENCIL_ATTACHMENT
#define android_opengl_GLES20_GL_STENCIL_ATTACHMENT 36128L
#undef android_opengl_GLES20_GL_NONE
#define android_opengl_GLES20_GL_NONE 0L
#undef android_opengl_GLES20_GL_FRAMEBUFFER_COMPLETE
#define android_opengl_GLES20_GL_FRAMEBUFFER_COMPLETE 36053L
#undef android_opengl_GLES20_GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT
#define android_opengl_GLES20_GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT 36054L
#undef android_opengl_GLES20_GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT
#define android_opengl_GLES20_GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT 36055L
#undef android_opengl_GLES20_GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS
#define android_opengl_GLES20_GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS 36057L
#undef android_opengl_GLES20_GL_FRAMEBUFFER_UNSUPPORTED
#define android_opengl_GLES20_GL_FRAMEBUFFER_UNSUPPORTED 36061L
#undef android_opengl_GLES20_GL_FRAMEBUFFER_BINDING
#define android_opengl_GLES20_GL_FRAMEBUFFER_BINDING 36006L
#undef android_opengl_GLES20_GL_RENDERBUFFER_BINDING
#define android_opengl_GLES20_GL_RENDERBUFFER_BINDING 36007L
#undef android_opengl_GLES20_GL_MAX_RENDERBUFFER_SIZE
#define android_opengl_GLES20_GL_MAX_RENDERBUFFER_SIZE 34024L
#undef android_opengl_GLES20_GL_INVALID_FRAMEBUFFER_OPERATION
#define android_opengl_GLES20_GL_INVALID_FRAMEBUFFER_OPERATION 1286L
/*
 * Class:     android_opengl_GLES20
 * Method:    glActiveTexture
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glActiveTexture
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glAttachShader
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glAttachShader
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glBindAttribLocation
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glBindAttribLocation
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     android_opengl_GLES20
 * Method:    glBindBuffer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glBindBuffer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glBindFramebuffer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glBindFramebuffer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glBindRenderbuffer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glBindRenderbuffer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glBindTexture
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glBindTexture
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glBlendColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glBlendColor
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_opengl_GLES20
 * Method:    glBlendEquation
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glBlendEquation
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glBlendEquationSeparate
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glBlendEquationSeparate
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glBlendFunc
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glBlendFunc
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glBlendFuncSeparate
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glBlendFuncSeparate
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glBufferData
 * Signature: (IILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glBufferData
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glBufferSubData
 * Signature: (IIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glBufferSubData
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glCheckFramebufferStatus
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_android_opengl_GLES20_glCheckFramebufferStatus
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glClear
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glClear
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glClearColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glClearColor
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_opengl_GLES20
 * Method:    glClearDepthf
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glClearDepthf
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     android_opengl_GLES20
 * Method:    glClearStencil
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glClearStencil
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glColorMask
 * Signature: (ZZZZ)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glColorMask
  (JNIEnv *, jclass, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     android_opengl_GLES20
 * Method:    glCompileShader
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glCompileShader
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glCompressedTexImage2D
 * Signature: (IIIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glCompressedTexImage2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glCompressedTexSubImage2D
 * Signature: (IIIIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glCompressedTexSubImage2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glCopyTexImage2D
 * Signature: (IIIIIIII)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glCopyTexImage2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glCopyTexSubImage2D
 * Signature: (IIIIIIII)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glCopyTexSubImage2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glCreateProgram
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_android_opengl_GLES20_glCreateProgram
  (JNIEnv *, jclass);

/*
 * Class:     android_opengl_GLES20
 * Method:    glCreateShader
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_android_opengl_GLES20_glCreateShader
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glCullFace
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glCullFace
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glDeleteBuffers
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glDeleteBuffers__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glDeleteBuffers
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glDeleteBuffers__ILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glDeleteFramebuffers
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glDeleteFramebuffers__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glDeleteFramebuffers
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glDeleteFramebuffers__ILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glDeleteProgram
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glDeleteProgram
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glDeleteRenderbuffers
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glDeleteRenderbuffers__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glDeleteRenderbuffers
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glDeleteRenderbuffers__ILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glDeleteShader
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glDeleteShader
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glDeleteTextures
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glDeleteTextures__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glDeleteTextures
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glDeleteTextures__ILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glDepthFunc
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glDepthFunc
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glDepthMask
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glDepthMask
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     android_opengl_GLES20
 * Method:    glDepthRangef
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glDepthRangef
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     android_opengl_GLES20
 * Method:    glDetachShader
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glDetachShader
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glDisable
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glDisable
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glDisableVertexAttribArray
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glDisableVertexAttribArray
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glDrawArrays
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glDrawArrays
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glDrawElements
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glDrawElements__IIII
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glDrawElements
 * Signature: (IIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glDrawElements__IIILjava_nio_Buffer_2
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glEnable
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glEnable
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glEnableVertexAttribArray
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glEnableVertexAttribArray
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glFinish
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glFinish
  (JNIEnv *, jclass);

/*
 * Class:     android_opengl_GLES20
 * Method:    glFlush
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glFlush
  (JNIEnv *, jclass);

/*
 * Class:     android_opengl_GLES20
 * Method:    glFramebufferRenderbuffer
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glFramebufferRenderbuffer
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glFramebufferTexture2D
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glFramebufferTexture2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glFrontFace
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glFrontFace
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGenBuffers
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGenBuffers__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGenBuffers
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGenBuffers__ILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGenerateMipmap
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGenerateMipmap
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGenFramebuffers
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGenFramebuffers__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGenFramebuffers
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGenFramebuffers__ILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGenRenderbuffers
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGenRenderbuffers__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGenRenderbuffers
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGenRenderbuffers__ILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGenTextures
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGenTextures__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGenTextures
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGenTextures__ILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetActiveAttrib
 * Signature: (III[II[II[II[BI)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetActiveAttrib__III_3II_3II_3II_3BI
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jint, jintArray, jint, jintArray, jint, jbyteArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetActiveAttrib
 * Signature: (IIILjava/nio/IntBuffer;Ljava/nio/IntBuffer;Ljava/nio/IntBuffer;B)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetActiveAttrib__IIILjava_nio_IntBuffer_2Ljava_nio_IntBuffer_2Ljava_nio_IntBuffer_2B
  (JNIEnv *, jclass, jint, jint, jint, jobject, jobject, jobject, jbyte);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetActiveAttrib
 * Signature: (II[II[II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_android_opengl_GLES20_glGetActiveAttrib__II_3II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint, jintArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetActiveAttrib
 * Signature: (IILjava/nio/IntBuffer;Ljava/nio/IntBuffer;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_android_opengl_GLES20_glGetActiveAttrib__IILjava_nio_IntBuffer_2Ljava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetActiveUniform
 * Signature: (III[II[II[II[BI)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetActiveUniform__III_3II_3II_3II_3BI
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jint, jintArray, jint, jintArray, jint, jbyteArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetActiveUniform
 * Signature: (IIILjava/nio/IntBuffer;Ljava/nio/IntBuffer;Ljava/nio/IntBuffer;B)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetActiveUniform__IIILjava_nio_IntBuffer_2Ljava_nio_IntBuffer_2Ljava_nio_IntBuffer_2B
  (JNIEnv *, jclass, jint, jint, jint, jobject, jobject, jobject, jbyte);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetActiveUniform
 * Signature: (II[II[II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_android_opengl_GLES20_glGetActiveUniform__II_3II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint, jintArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetActiveUniform
 * Signature: (IILjava/nio/IntBuffer;Ljava/nio/IntBuffer;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_android_opengl_GLES20_glGetActiveUniform__IILjava_nio_IntBuffer_2Ljava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetAttachedShaders
 * Signature: (II[II[II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetAttachedShaders__II_3II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint, jintArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetAttachedShaders
 * Signature: (IILjava/nio/IntBuffer;Ljava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetAttachedShaders__IILjava_nio_IntBuffer_2Ljava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetAttribLocation
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_android_opengl_GLES20_glGetAttribLocation
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetBooleanv
 * Signature: (I[ZI)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetBooleanv__I_3ZI
  (JNIEnv *, jclass, jint, jbooleanArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetBooleanv
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetBooleanv__ILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetBufferParameteriv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetBufferParameteriv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetBufferParameteriv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetBufferParameteriv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_android_opengl_GLES20_glGetError
  (JNIEnv *, jclass);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetFloatv
 * Signature: (I[FI)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetFloatv__I_3FI
  (JNIEnv *, jclass, jint, jfloatArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetFloatv
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetFloatv__ILjava_nio_FloatBuffer_2
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetFramebufferAttachmentParameteriv
 * Signature: (III[II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetFramebufferAttachmentParameteriv__III_3II
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetFramebufferAttachmentParameteriv
 * Signature: (IIILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetFramebufferAttachmentParameteriv__IIILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetIntegerv
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetIntegerv__I_3II
  (JNIEnv *, jclass, jint, jintArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetIntegerv
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetIntegerv__ILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetProgramiv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetProgramiv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetProgramiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetProgramiv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetProgramInfoLog
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_android_opengl_GLES20_glGetProgramInfoLog
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetRenderbufferParameteriv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetRenderbufferParameteriv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetRenderbufferParameteriv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetRenderbufferParameteriv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetShaderiv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetShaderiv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetShaderiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetShaderiv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetShaderInfoLog
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_android_opengl_GLES20_glGetShaderInfoLog
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetShaderPrecisionFormat
 * Signature: (II[II[II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetShaderPrecisionFormat__II_3II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint, jintArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetShaderPrecisionFormat
 * Signature: (IILjava/nio/IntBuffer;Ljava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetShaderPrecisionFormat__IILjava_nio_IntBuffer_2Ljava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetShaderSource
 * Signature: (II[II[BI)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetShaderSource__II_3II_3BI
  (JNIEnv *, jclass, jint, jint, jintArray, jint, jbyteArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetShaderSource
 * Signature: (IILjava/nio/IntBuffer;B)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetShaderSource__IILjava_nio_IntBuffer_2B
  (JNIEnv *, jclass, jint, jint, jobject, jbyte);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetShaderSource
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_android_opengl_GLES20_glGetShaderSource__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_android_opengl_GLES20_glGetString
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetTexParameterfv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetTexParameterfv__II_3FI
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetTexParameterfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetTexParameterfv__IILjava_nio_FloatBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetTexParameteriv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetTexParameteriv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetTexParameteriv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetTexParameteriv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetUniformfv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetUniformfv__II_3FI
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetUniformfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetUniformfv__IILjava_nio_FloatBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetUniformiv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetUniformiv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetUniformiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetUniformiv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetUniformLocation
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_android_opengl_GLES20_glGetUniformLocation
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetVertexAttribfv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetVertexAttribfv__II_3FI
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetVertexAttribfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetVertexAttribfv__IILjava_nio_FloatBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetVertexAttribiv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetVertexAttribiv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glGetVertexAttribiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glGetVertexAttribiv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glHint
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glHint
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glIsBuffer
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_android_opengl_GLES20_glIsBuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glIsEnabled
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_android_opengl_GLES20_glIsEnabled
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glIsFramebuffer
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_android_opengl_GLES20_glIsFramebuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glIsProgram
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_android_opengl_GLES20_glIsProgram
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glIsRenderbuffer
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_android_opengl_GLES20_glIsRenderbuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glIsShader
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_android_opengl_GLES20_glIsShader
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glIsTexture
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_android_opengl_GLES20_glIsTexture
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glLineWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glLineWidth
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     android_opengl_GLES20
 * Method:    glLinkProgram
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glLinkProgram
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glPixelStorei
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glPixelStorei
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glPolygonOffset
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glPolygonOffset
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     android_opengl_GLES20
 * Method:    glReadPixels
 * Signature: (IIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glReadPixels
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glReleaseShaderCompiler
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glReleaseShaderCompiler
  (JNIEnv *, jclass);

/*
 * Class:     android_opengl_GLES20
 * Method:    glRenderbufferStorage
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glRenderbufferStorage
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glSampleCoverage
 * Signature: (FZ)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glSampleCoverage
  (JNIEnv *, jclass, jfloat, jboolean);

/*
 * Class:     android_opengl_GLES20
 * Method:    glScissor
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glScissor
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glShaderBinary
 * Signature: (I[IIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glShaderBinary__I_3IIILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jintArray, jint, jint, jobject, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glShaderBinary
 * Signature: (ILjava/nio/IntBuffer;ILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glShaderBinary__ILjava_nio_IntBuffer_2ILjava_nio_Buffer_2I
  (JNIEnv *, jclass, jint, jobject, jint, jobject, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glShaderSource
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glShaderSource
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     android_opengl_GLES20
 * Method:    glStencilFunc
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glStencilFunc
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glStencilFuncSeparate
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glStencilFuncSeparate
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glStencilMask
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glStencilMask
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glStencilMaskSeparate
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glStencilMaskSeparate
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glStencilOp
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glStencilOp
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glStencilOpSeparate
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glStencilOpSeparate
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glTexImage2D
 * Signature: (IIIIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glTexImage2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glTexParameterf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glTexParameterf
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     android_opengl_GLES20
 * Method:    glTexParameterfv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glTexParameterfv__II_3FI
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glTexParameterfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glTexParameterfv__IILjava_nio_FloatBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glTexParameteri
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glTexParameteri
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glTexParameteriv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glTexParameteriv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glTexParameteriv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glTexParameteriv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glTexSubImage2D
 * Signature: (IIIIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glTexSubImage2D
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glUniform1f
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glUniform1f
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     android_opengl_GLES20
 * Method:    glUniform1fv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glUniform1fv__II_3FI
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glUniform1fv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glUniform1fv__IILjava_nio_FloatBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glUniform1i
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glUniform1i
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glUniform1iv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glUniform1iv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glUniform1iv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glUniform1iv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glUniform2f
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glUniform2f
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     android_opengl_GLES20
 * Method:    glUniform2fv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glUniform2fv__II_3FI
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glUniform2fv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glUniform2fv__IILjava_nio_FloatBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glUniform2i
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glUniform2i
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glUniform2iv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glUniform2iv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glUniform2iv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glUniform2iv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glUniform3f
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glUniform3f
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     android_opengl_GLES20
 * Method:    glUniform3fv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glUniform3fv__II_3FI
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glUniform3fv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glUniform3fv__IILjava_nio_FloatBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glUniform3i
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glUniform3i
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glUniform3iv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glUniform3iv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glUniform3iv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glUniform3iv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glUniform4f
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glUniform4f
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_opengl_GLES20
 * Method:    glUniform4fv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glUniform4fv__II_3FI
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glUniform4fv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glUniform4fv__IILjava_nio_FloatBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glUniform4i
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glUniform4i
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glUniform4iv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glUniform4iv__II_3II
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glUniform4iv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glUniform4iv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glUniformMatrix2fv
 * Signature: (IIZ[FI)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glUniformMatrix2fv__IIZ_3FI
  (JNIEnv *, jclass, jint, jint, jboolean, jfloatArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glUniformMatrix2fv
 * Signature: (IIZLjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glUniformMatrix2fv__IIZLjava_nio_FloatBuffer_2
  (JNIEnv *, jclass, jint, jint, jboolean, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glUniformMatrix3fv
 * Signature: (IIZ[FI)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glUniformMatrix3fv__IIZ_3FI
  (JNIEnv *, jclass, jint, jint, jboolean, jfloatArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glUniformMatrix3fv
 * Signature: (IIZLjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glUniformMatrix3fv__IIZLjava_nio_FloatBuffer_2
  (JNIEnv *, jclass, jint, jint, jboolean, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glUniformMatrix4fv
 * Signature: (IIZ[FI)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glUniformMatrix4fv__IIZ_3FI
  (JNIEnv *, jclass, jint, jint, jboolean, jfloatArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glUniformMatrix4fv
 * Signature: (IIZLjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glUniformMatrix4fv__IIZLjava_nio_FloatBuffer_2
  (JNIEnv *, jclass, jint, jint, jboolean, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glUseProgram
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glUseProgram
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glValidateProgram
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glValidateProgram
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glVertexAttrib1f
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glVertexAttrib1f
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     android_opengl_GLES20
 * Method:    glVertexAttrib1fv
 * Signature: (I[FI)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glVertexAttrib1fv__I_3FI
  (JNIEnv *, jclass, jint, jfloatArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glVertexAttrib1fv
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glVertexAttrib1fv__ILjava_nio_FloatBuffer_2
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glVertexAttrib2f
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glVertexAttrib2f
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     android_opengl_GLES20
 * Method:    glVertexAttrib2fv
 * Signature: (I[FI)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glVertexAttrib2fv__I_3FI
  (JNIEnv *, jclass, jint, jfloatArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glVertexAttrib2fv
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glVertexAttrib2fv__ILjava_nio_FloatBuffer_2
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glVertexAttrib3f
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glVertexAttrib3f
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     android_opengl_GLES20
 * Method:    glVertexAttrib3fv
 * Signature: (I[FI)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glVertexAttrib3fv__I_3FI
  (JNIEnv *, jclass, jint, jfloatArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glVertexAttrib3fv
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glVertexAttrib3fv__ILjava_nio_FloatBuffer_2
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glVertexAttrib4f
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glVertexAttrib4f
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_opengl_GLES20
 * Method:    glVertexAttrib4fv
 * Signature: (I[FI)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glVertexAttrib4fv__I_3FI
  (JNIEnv *, jclass, jint, jfloatArray, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glVertexAttrib4fv
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glVertexAttrib4fv__ILjava_nio_FloatBuffer_2
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     android_opengl_GLES20
 * Method:    glVertexAttribPointer
 * Signature: (IIIZII)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glVertexAttribPointer
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jint, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glVertexAttribPointerBounds
 * Signature: (IIIZILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glVertexAttribPointerBounds
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jint, jobject, jint);

/*
 * Class:     android_opengl_GLES20
 * Method:    glViewport
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_android_opengl_GLES20_glViewport
  (JNIEnv *, jclass, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
