/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_os_MessageQueue */

#ifndef _Included_android_os_MessageQueue
#define _Included_android_os_MessageQueue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_os_MessageQueue
 * Method:    nativeInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_os_MessageQueue_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     android_os_MessageQueue
 * Method:    nativeDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_os_MessageQueue_nativeDestroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_os_MessageQueue
 * Method:    nativePollOnce
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_android_os_MessageQueue_nativePollOnce
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_os_MessageQueue
 * Method:    nativeWake
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_os_MessageQueue_nativeWake
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_os_MessageQueue
 * Method:    nativeIsIdling
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_android_os_MessageQueue_nativeIsIdling
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
