/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_content_ContentResolver */

#ifndef _Included_android_content_ContentResolver
#define _Included_android_content_ContentResolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_content_ContentResolver
 * Method:    native_query_file_info
 * Signature: (Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_android_content_ContentResolver_native_1query_1file_1info
  (JNIEnv *, jclass, jstring, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
