/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_media_AudioRecord */

#ifndef _Included_android_media_AudioRecord
#define _Included_android_media_AudioRecord
#ifdef __cplusplus
extern "C" {
#endif
#undef android_media_AudioRecord_RECORDSTATE_STOPPED
#define android_media_AudioRecord_RECORDSTATE_STOPPED 1L
#undef android_media_AudioRecord_RECORDSTATE_RECORDING
#define android_media_AudioRecord_RECORDSTATE_RECORDING 3L
#undef android_media_AudioRecord_ERROR_BAD_VALUE
#define android_media_AudioRecord_ERROR_BAD_VALUE -2L
/*
 * Class:     android_media_AudioRecord
 * Method:    native_constructor
 * Signature: (IIIII)J
 */
JNIEXPORT jlong JNICALL Java_android_media_AudioRecord_native_1constructor
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     android_media_AudioRecord
 * Method:    native_record
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_media_AudioRecord_native_1record
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_media_AudioRecord
 * Method:    native_stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_media_AudioRecord_native_1stop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_media_AudioRecord
 * Method:    native_read
 * Signature: (J[SII)I
 */
JNIEXPORT jint JNICALL Java_android_media_AudioRecord_native_1read
  (JNIEnv *, jobject, jlong, jshortArray, jint, jint);

/*
 * Class:     android_media_AudioRecord
 * Method:    native_release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_media_AudioRecord_native_1release
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_media_AudioRecord
 * Method:    getMinBufferSize
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_android_media_AudioRecord_getMinBufferSize
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
