/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_atl_GVariantBuilderParcel */

#ifndef _Included_android_atl_GVariantBuilderParcel
#define _Included_android_atl_GVariantBuilderParcel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_atl_GVariantBuilderParcel
 * Method:    native_writeByte
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_android_atl_GVariantBuilderParcel_native_1writeByte
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     android_atl_GVariantBuilderParcel
 * Method:    native_writeInt
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_android_atl_GVariantBuilderParcel_native_1writeInt
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_atl_GVariantBuilderParcel
 * Method:    native_writeString
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_atl_GVariantBuilderParcel_native_1writeString
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
