/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_media_MediaPlayer */

#ifndef _Included_android_media_MediaPlayer
#define _Included_android_media_MediaPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_media_MediaPlayer
 * Method:    native_prepare
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_media_MediaPlayer_native_1prepare
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_media_MediaPlayer
 * Method:    native_setDataSource
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_android_media_MediaPlayer_native_1setDataSource
  (JNIEnv *, jobject, jstring);

/*
 * Class:     android_media_MediaPlayer
 * Method:    native_setOnCompletionListener
 * Signature: (JLandroid/media/MediaPlayer/OnCompletionListener;)V
 */
JNIEXPORT void JNICALL Java_android_media_MediaPlayer_native_1setOnCompletionListener
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     android_media_MediaPlayer
 * Method:    native_start
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_media_MediaPlayer_native_1start
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_media_MediaPlayer
 * Method:    native_getDuration
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_android_media_MediaPlayer_native_1getDuration
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_media_MediaPlayer
 * Method:    native_getCurrentPosition
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_android_media_MediaPlayer_native_1getCurrentPosition
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
