/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_android_gles_jni_EGLImpl */

#ifndef _Included_com_google_android_gles_jni_EGLImpl
#define _Included_com_google_android_gles_jni_EGLImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_google_android_gles_jni_EGLImpl
 * Method:    native_eglCreateContext
 * Signature: (JJJ[I)J
 */
JNIEXPORT jlong JNICALL Java_com_google_android_gles_1jni_EGLImpl_native_1eglCreateContext
  (JNIEnv *, jobject, jlong, jlong, jlong, jintArray);

/*
 * Class:     com_google_android_gles_jni_EGLImpl
 * Method:    native_eglChooseConfig
 * Signature: (J[I[JI[I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_google_android_gles_1jni_EGLImpl_native_1eglChooseConfig
  (JNIEnv *, jobject, jlong, jintArray, jlongArray, jint, jintArray);

/*
 * Class:     com_google_android_gles_jni_EGLImpl
 * Method:    native_eglCreateWindowSurface
 * Signature: (JJLandroid/view/Surface;[I)J
 */
JNIEXPORT jlong JNICALL Java_com_google_android_gles_1jni_EGLImpl_native_1eglCreateWindowSurface
  (JNIEnv *, jobject, jlong, jlong, jobject, jintArray);

/*
 * Class:     com_google_android_gles_jni_EGLImpl
 * Method:    native_eglGetDisplay
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_com_google_android_gles_1jni_EGLImpl_native_1eglGetDisplay
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_google_android_gles_jni_EGLImpl
 * Method:    native_eglInitialize
 * Signature: (J[I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_google_android_gles_1jni_EGLImpl_native_1eglInitialize
  (JNIEnv *, jobject, jlong, jintArray);

/*
 * Class:     com_google_android_gles_jni_EGLImpl
 * Method:    native_eglGetConfigAttrib
 * Signature: (JJI[I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_google_android_gles_1jni_EGLImpl_native_1eglGetConfigAttrib
  (JNIEnv *, jobject, jlong, jlong, jint, jintArray);

/*
 * Class:     com_google_android_gles_jni_EGLImpl
 * Method:    native_eglMakeCurrent
 * Signature: (JJJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_google_android_gles_1jni_EGLImpl_native_1eglMakeCurrent
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     com_google_android_gles_jni_EGLImpl
 * Method:    native_eglSwapBuffers
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_google_android_gles_1jni_EGLImpl_native_1eglSwapBuffers
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_google_android_gles_jni_EGLImpl
 * Method:    native_eglDestroySurface
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_google_android_gles_1jni_EGLImpl_native_1eglDestroySurface
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_google_android_gles_jni_EGLImpl
 * Method:    native_eglDestroyContext
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_google_android_gles_1jni_EGLImpl_native_1eglDestroyContext
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_google_android_gles_jni_EGLImpl
 * Method:    native_eglCreatePbufferSurface
 * Signature: (JJ[I)J
 */
JNIEXPORT jlong JNICALL Java_com_google_android_gles_1jni_EGLImpl_native_1eglCreatePbufferSurface
  (JNIEnv *, jobject, jlong, jlong, jintArray);

#ifdef __cplusplus
}
#endif
#endif
