/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_android_gles_jni_GLImpl */

#ifndef _Included_com_google_android_gles_jni_GLImpl
#define _Included_com_google_android_gles_jni_GLImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glActiveTexture
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glActiveTexture
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glAlphaFunc
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glAlphaFunc
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glAlphaFuncx
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glAlphaFuncx
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glBlendFunc
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glBlendFunc
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glClearColorx
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glClearColorx
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glClearDepthf
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glClearDepthf
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glClearDepthx
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glClearDepthx
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glClearStencil
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glClearStencil
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glClientActiveTexture
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glClientActiveTexture
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glColor4f
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glColor4f
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glColor4x
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glColor4x
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glColorMask
 * Signature: (ZZZZ)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glColorMask
  (JNIEnv *, jobject, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glColorPointerBounds
 * Signature: (IIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glColorPointerBounds
  (JNIEnv *, jobject, jint, jint, jint, jobject, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glCompressedTexImage2D
 * Signature: (IIIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glCompressedTexImage2D
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glCompressedTexSubImage2D
 * Signature: (IIIIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glCompressedTexSubImage2D
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glCopyTexImage2D
 * Signature: (IIIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glCopyTexImage2D
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glCopyTexSubImage2D
 * Signature: (IIIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glCopyTexSubImage2D
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glCullFace
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glCullFace
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glDepthFunc
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glDepthFunc
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glDepthMask
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glDepthMask
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glDepthRangef
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glDepthRangef
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glDepthRangex
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glDepthRangex
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glDisableClientState
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glDisableClientState
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glDrawArrays
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glDrawArrays
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glEnableClientState
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glEnableClientState
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glFinish
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glFinish
  (JNIEnv *, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glFogf
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glFogf
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glFogfv
 * Signature: (I[FI)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glFogfv__I_3FI
  (JNIEnv *, jobject, jint, jfloatArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glFogfv
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glFogfv__ILjava_nio_FloatBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glFogx
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glFogx
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glFogxv
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glFogxv__I_3II
  (JNIEnv *, jobject, jint, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glFogxv
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glFogxv__ILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glFrustumf
 * Signature: (FFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glFrustumf
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glFrustumx
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glFrustumx
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGenTextures
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGenTextures
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetError
  (JNIEnv *, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetIntegerv
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetIntegerv__I_3II
  (JNIEnv *, jobject, jint, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetIntegerv
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetIntegerv__ILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    _glGetString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_google_android_gles_1jni_GLImpl__1glGetString
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glHint
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glHint
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glLightModelf
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glLightModelf
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glLightModelfv
 * Signature: (I[FI)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glLightModelfv__I_3FI
  (JNIEnv *, jobject, jint, jfloatArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glLightModelfv
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glLightModelfv__ILjava_nio_FloatBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glLightModelx
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glLightModelx
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glLightModelxv
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glLightModelxv__I_3II
  (JNIEnv *, jobject, jint, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glLightModelxv
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glLightModelxv__ILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glLightf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glLightf
  (JNIEnv *, jobject, jint, jint, jfloat);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glLightfv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glLightfv__II_3FI
  (JNIEnv *, jobject, jint, jint, jfloatArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glLightfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glLightfv__IILjava_nio_FloatBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glLightx
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glLightx
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glLightxv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glLightxv__II_3II
  (JNIEnv *, jobject, jint, jint, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glLightxv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glLightxv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glLineWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glLineWidth
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glLineWidthx
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glLineWidthx
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glLoadIdentity
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glLoadIdentity
  (JNIEnv *, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glLoadMatrixf
 * Signature: ([FI)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glLoadMatrixf___3FI
  (JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glLoadMatrixf
 * Signature: (Ljava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glLoadMatrixf__Ljava_nio_FloatBuffer_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glLoadMatrixx
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glLoadMatrixx___3II
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glLoadMatrixx
 * Signature: (Ljava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glLoadMatrixx__Ljava_nio_IntBuffer_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glLogicOp
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glLogicOp
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glMaterialf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glMaterialf
  (JNIEnv *, jobject, jint, jint, jfloat);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glMaterialfv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glMaterialfv__II_3FI
  (JNIEnv *, jobject, jint, jint, jfloatArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glMaterialfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glMaterialfv__IILjava_nio_FloatBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glMaterialx
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glMaterialx
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glMaterialxv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glMaterialxv__II_3II
  (JNIEnv *, jobject, jint, jint, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glMaterialxv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glMaterialxv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glMatrixMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glMatrixMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glMultMatrixf
 * Signature: ([FI)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glMultMatrixf___3FI
  (JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glMultMatrixf
 * Signature: (Ljava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glMultMatrixf__Ljava_nio_FloatBuffer_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glMultMatrixx
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glMultMatrixx___3II
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glMultMatrixx
 * Signature: (Ljava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glMultMatrixx__Ljava_nio_IntBuffer_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glMultiTexCoord4f
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glMultiTexCoord4f
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glMultiTexCoord4x
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glMultiTexCoord4x
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glNormal3f
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glNormal3f
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glNormal3x
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glNormal3x
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glNormalPointerBounds
 * Signature: (IILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glNormalPointerBounds
  (JNIEnv *, jobject, jint, jint, jobject, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glOrthof
 * Signature: (FFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glOrthof
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glOrthox
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glOrthox
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glPixelStorei
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glPixelStorei
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glPointSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glPointSize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glPointSizex
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glPointSizex
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glPolygonOffset
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glPolygonOffset
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glPolygonOffsetx
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glPolygonOffsetx
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glPopMatrix
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glPopMatrix
  (JNIEnv *, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glPushMatrix
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glPushMatrix
  (JNIEnv *, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glRotatef
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glRotatef
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glRotatex
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glRotatex
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glSampleCoverage
 * Signature: (FZ)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glSampleCoverage
  (JNIEnv *, jobject, jfloat, jboolean);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glSampleCoveragex
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glSampleCoveragex
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glScalef
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glScalef
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glScalex
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glScalex
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glScissor
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glScissor
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glShadeModel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glShadeModel
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glStencilFunc
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glStencilFunc
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glStencilMask
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glStencilMask
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glStencilOp
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glStencilOp
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glTexCoordPointerBounds
 * Signature: (IIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glTexCoordPointerBounds
  (JNIEnv *, jobject, jint, jint, jint, jobject, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glTexEnvf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glTexEnvf
  (JNIEnv *, jobject, jint, jint, jfloat);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glTexEnvfv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glTexEnvfv__II_3FI
  (JNIEnv *, jobject, jint, jint, jfloatArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glTexEnvfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glTexEnvfv__IILjava_nio_FloatBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glTexEnvx
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glTexEnvx
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glTexEnvxv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glTexEnvxv__II_3II
  (JNIEnv *, jobject, jint, jint, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glTexEnvxv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glTexEnvxv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glTexImage2D
 * Signature: (IIIIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glTexImage2D
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glTexParameterx
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glTexParameterx
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glTexSubImage2D
 * Signature: (IIIIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glTexSubImage2D
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glTranslatef
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glTranslatef
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glTranslatex
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glTranslatex
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glVertexPointerBounds
 * Signature: (IIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glVertexPointerBounds
  (JNIEnv *, jobject, jint, jint, jint, jobject, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glQueryMatrixxOES
 * Signature: ([II[II)I
 */
JNIEXPORT jint JNICALL Java_com_google_android_gles_1jni_GLImpl_glQueryMatrixxOES___3II_3II
  (JNIEnv *, jobject, jintArray, jint, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glQueryMatrixxOES
 * Signature: (Ljava/nio/IntBuffer;Ljava/nio/IntBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_google_android_gles_1jni_GLImpl_glQueryMatrixxOES__Ljava_nio_IntBuffer_2Ljava_nio_IntBuffer_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glBindBuffer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glBindBuffer
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glBufferData
 * Signature: (IILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glBufferData
  (JNIEnv *, jobject, jint, jint, jobject, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glBufferSubData
 * Signature: (IIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glBufferSubData
  (JNIEnv *, jobject, jint, jint, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glClipPlanef
 * Signature: (I[FI)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glClipPlanef__I_3FI
  (JNIEnv *, jobject, jint, jfloatArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glClipPlanef
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glClipPlanef__ILjava_nio_FloatBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glClipPlanex
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glClipPlanex__I_3II
  (JNIEnv *, jobject, jint, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glClipPlanex
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glClipPlanex__ILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glColor4ub
 * Signature: (BBBB)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glColor4ub
  (JNIEnv *, jobject, jbyte, jbyte, jbyte, jbyte);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glColorPointer
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glColorPointer
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glDeleteBuffers
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glDeleteBuffers__I_3II
  (JNIEnv *, jobject, jint, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glDeleteBuffers
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glDeleteBuffers__ILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glDrawElements
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glDrawElements
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGenBuffers
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGenBuffers__I_3II
  (JNIEnv *, jobject, jint, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGenBuffers
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGenBuffers__ILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetBooleanv
 * Signature: (I[ZI)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetBooleanv__I_3ZI
  (JNIEnv *, jobject, jint, jbooleanArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetBooleanv
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetBooleanv__ILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetBufferParameteriv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetBufferParameteriv__II_3II
  (JNIEnv *, jobject, jint, jint, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetBufferParameteriv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetBufferParameteriv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetClipPlanef
 * Signature: (I[FI)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetClipPlanef__I_3FI
  (JNIEnv *, jobject, jint, jfloatArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetClipPlanef
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetClipPlanef__ILjava_nio_FloatBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetClipPlanex
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetClipPlanex__I_3II
  (JNIEnv *, jobject, jint, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetClipPlanex
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetClipPlanex__ILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetFixedv
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetFixedv__I_3II
  (JNIEnv *, jobject, jint, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetFixedv
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetFixedv__ILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetFloatv
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetFloatv
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetLightfv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetLightfv__II_3FI
  (JNIEnv *, jobject, jint, jint, jfloatArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetLightfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetLightfv__IILjava_nio_FloatBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetLightxv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetLightxv__II_3II
  (JNIEnv *, jobject, jint, jint, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetLightxv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetLightxv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetMaterialfv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetMaterialfv__II_3FI
  (JNIEnv *, jobject, jint, jint, jfloatArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetMaterialfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetMaterialfv__IILjava_nio_FloatBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetMaterialxv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetMaterialxv__II_3II
  (JNIEnv *, jobject, jint, jint, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetMaterialxv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetMaterialxv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetTexEnviv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetTexEnviv__II_3II
  (JNIEnv *, jobject, jint, jint, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetTexEnviv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetTexEnviv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetTexEnvxv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetTexEnvxv__II_3II
  (JNIEnv *, jobject, jint, jint, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetTexEnvxv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetTexEnvxv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetTexParameterfv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetTexParameterfv__II_3FI
  (JNIEnv *, jobject, jint, jint, jfloatArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetTexParameterfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetTexParameterfv__IILjava_nio_FloatBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetTexParameteriv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetTexParameteriv__II_3II
  (JNIEnv *, jobject, jint, jint, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetTexParameteriv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetTexParameteriv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetTexParameterxv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetTexParameterxv__II_3II
  (JNIEnv *, jobject, jint, jint, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetTexParameterxv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetTexParameterxv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glIsBuffer
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_google_android_gles_1jni_GLImpl_glIsBuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glIsEnabled
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_google_android_gles_1jni_GLImpl_glIsEnabled
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glIsTexture
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_google_android_gles_1jni_GLImpl_glIsTexture
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glNormalPointer
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glNormalPointer
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glPointParameterf
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glPointParameterf
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glPointParameterfv
 * Signature: (I[FI)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glPointParameterfv__I_3FI
  (JNIEnv *, jobject, jint, jfloatArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glPointParameterfv
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glPointParameterfv__ILjava_nio_FloatBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glPointParameterx
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glPointParameterx
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glPointParameterxv
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glPointParameterxv__I_3II
  (JNIEnv *, jobject, jint, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glPointParameterxv
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glPointParameterxv__ILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glPointSizePointerOESBounds
 * Signature: (IILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glPointSizePointerOESBounds
  (JNIEnv *, jobject, jint, jint, jobject, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glTexCoordPointer
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glTexCoordPointer
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glTexEnvi
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glTexEnvi
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glTexEnviv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glTexEnviv__II_3II
  (JNIEnv *, jobject, jint, jint, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glTexEnviv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glTexEnviv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glTexParameterfv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glTexParameterfv__II_3FI
  (JNIEnv *, jobject, jint, jint, jfloatArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glTexParameterfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glTexParameterfv__IILjava_nio_FloatBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glTexParameteri
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glTexParameteri
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glTexParameteriv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glTexParameteriv__II_3II
  (JNIEnv *, jobject, jint, jint, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glTexParameteriv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glTexParameteriv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glTexParameterxv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glTexParameterxv__II_3II
  (JNIEnv *, jobject, jint, jint, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glTexParameterxv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glTexParameterxv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glVertexPointer
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glVertexPointer
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glCurrentPaletteMatrixOES
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glCurrentPaletteMatrixOES
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glDrawTexfOES
 * Signature: (FFFFF)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glDrawTexfOES
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glDrawTexfvOES
 * Signature: ([FI)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glDrawTexfvOES___3FI
  (JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glDrawTexfvOES
 * Signature: (Ljava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glDrawTexfvOES__Ljava_nio_FloatBuffer_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glDrawTexiOES
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glDrawTexiOES
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glDrawTexivOES
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glDrawTexivOES___3II
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glDrawTexivOES
 * Signature: (Ljava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glDrawTexivOES__Ljava_nio_IntBuffer_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glDrawTexsOES
 * Signature: (SSSSS)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glDrawTexsOES
  (JNIEnv *, jobject, jshort, jshort, jshort, jshort, jshort);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glDrawTexsvOES
 * Signature: ([SI)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glDrawTexsvOES___3SI
  (JNIEnv *, jobject, jshortArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glDrawTexsvOES
 * Signature: (Ljava/nio/ShortBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glDrawTexsvOES__Ljava_nio_ShortBuffer_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glDrawTexxOES
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glDrawTexxOES
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glDrawTexxvOES
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glDrawTexxvOES___3II
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glDrawTexxvOES
 * Signature: (Ljava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glDrawTexxvOES__Ljava_nio_IntBuffer_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glLoadPaletteFromModelViewMatrixOES
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glLoadPaletteFromModelViewMatrixOES
  (JNIEnv *, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glMatrixIndexPointerOESBounds
 * Signature: (IIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glMatrixIndexPointerOESBounds
  (JNIEnv *, jobject, jint, jint, jint, jobject, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glMatrixIndexPointerOES
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glMatrixIndexPointerOES
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glWeightPointerOESBounds
 * Signature: (IIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glWeightPointerOESBounds
  (JNIEnv *, jobject, jint, jint, jint, jobject, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glWeightPointerOES
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glWeightPointerOES
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glBindFramebufferOES
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glBindFramebufferOES
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glBindRenderbufferOES
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glBindRenderbufferOES
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glBlendEquation
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glBlendEquation
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glBlendEquationSeparate
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glBlendEquationSeparate
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glBlendFuncSeparate
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glBlendFuncSeparate
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glCheckFramebufferStatusOES
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_google_android_gles_1jni_GLImpl_glCheckFramebufferStatusOES
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glDeleteFramebuffersOES
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glDeleteFramebuffersOES__I_3II
  (JNIEnv *, jobject, jint, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glDeleteFramebuffersOES
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glDeleteFramebuffersOES__ILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glDeleteRenderbuffersOES
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glDeleteRenderbuffersOES__I_3II
  (JNIEnv *, jobject, jint, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glDeleteRenderbuffersOES
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glDeleteRenderbuffersOES__ILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glFramebufferRenderbufferOES
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glFramebufferRenderbufferOES
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glFramebufferTexture2DOES
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glFramebufferTexture2DOES
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGenerateMipmapOES
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGenerateMipmapOES
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGenFramebuffersOES
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGenFramebuffersOES__I_3II
  (JNIEnv *, jobject, jint, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGenFramebuffersOES
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGenFramebuffersOES__ILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGenRenderbuffersOES
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGenRenderbuffersOES__I_3II
  (JNIEnv *, jobject, jint, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGenRenderbuffersOES
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGenRenderbuffersOES__ILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetFramebufferAttachmentParameterivOES
 * Signature: (III[II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetFramebufferAttachmentParameterivOES__III_3II
  (JNIEnv *, jobject, jint, jint, jint, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetFramebufferAttachmentParameterivOES
 * Signature: (IIILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetFramebufferAttachmentParameterivOES__IIILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jint, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetRenderbufferParameterivOES
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetRenderbufferParameterivOES__II_3II
  (JNIEnv *, jobject, jint, jint, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetRenderbufferParameterivOES
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetRenderbufferParameterivOES__IILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetTexGenfv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetTexGenfv__II_3FI
  (JNIEnv *, jobject, jint, jint, jfloatArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetTexGenfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetTexGenfv__IILjava_nio_FloatBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetTexGeniv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetTexGeniv__II_3II
  (JNIEnv *, jobject, jint, jint, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetTexGeniv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetTexGeniv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetTexGenxv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetTexGenxv__II_3II
  (JNIEnv *, jobject, jint, jint, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glGetTexGenxv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glGetTexGenxv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glIsFramebufferOES
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_google_android_gles_1jni_GLImpl_glIsFramebufferOES
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glIsRenderbufferOES
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_google_android_gles_1jni_GLImpl_glIsRenderbufferOES
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glRenderbufferStorageOES
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glRenderbufferStorageOES
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glTexGenf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glTexGenf
  (JNIEnv *, jobject, jint, jint, jfloat);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glTexGenfv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glTexGenfv__II_3FI
  (JNIEnv *, jobject, jint, jint, jfloatArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glTexGenfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glTexGenfv__IILjava_nio_FloatBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glTexGeni
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glTexGeni
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glTexGeniv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glTexGeniv__II_3II
  (JNIEnv *, jobject, jint, jint, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glTexGeniv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glTexGeniv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glTexGenx
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glTexGenx
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glTexGenxv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glTexGenxv__II_3II
  (JNIEnv *, jobject, jint, jint, jintArray, jint);

/*
 * Class:     com_google_android_gles_jni_GLImpl
 * Method:    glTexGenxv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_google_android_gles_1jni_GLImpl_glTexGenxv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
